"""English B2: independent user — confident speech, nuance, repair."""

from curriculum_common import ex, lesson, word

LEVEL_B2 = [
    lesson(
        "narrative-tenses",
        {"en": "Narrative tenses: past simple, continuous, perfect", "ru": "Повествовательные времена: simple, continuous, perfect"},
        21,
        {
            "en": "Tell stories with past simple, continuous and perfect together, plus used to and would.",
            "ru": "Рассказывать историю: Past Simple + Continuous + Perfect в одной сцене, плюс used to / would про прошлое.",
        },
        [
            {"type": "p", "text": "На B2 история не должна «прыгать» без причины. Past Simple — скелет событий. Past Continuous — фон и прерванное действие. Past Perfect — то, что случилось ещё раньше. used to — привычки, которых больше нет. would — повторяющиеся действия в прошлом (не состояния вроде know/live в этом значении)."},
            {"type": "h2", "text": "Три оси на одной сцене"},
            {"type": "table", "headers": ["Время", "Роль", "Пример"], "rows": [
                ["Past Simple", "главные факты по порядку", "She opened the letter."],
                ["Past Continuous", "фон / параллель / прерывание", "She was sitting by the fire when it arrived."],
                ["Past Perfect", "раньше основного прошлого", "Someone had already broken the seal."],
                ["used to + V1", "бывшая привычка / состояние", "He used to live in Prague."],
                ["would + V1", "повторяющееся действие в прошлом", "Every evening he would light a cigar."],
            ]},
            {"type": "pattern", "text": "When + Past Simple, Past Continuous     ·     Past Perfect + before/already/by the time + Past Simple"},
            {"type": "example", "lang": "en", "en": "I was walking home when I realised I had left my keys at the office.", "ru": "фон → осознание → более ранний факт. Произнесите целиком — это шаблон B2-рассказа."},
            {"type": "h3", "text": "used to vs would"},
            {"type": "ul", "items": [
                "used to: и действия, и состояния: I used to be shy. I used to cycle to school.",
                "would: только повторяющиеся действия, часто с атмосферой воспоминания: On Sundays we would visit my grandparents.",
                "Отрицание привычки: didn't use to (не usedn't в современном стандарте курса).",
                "Вопрос: Did you use to…?",
            ]},
            {"type": "h2", "text": "By the time / already / just в прошлом"},
            {"type": "ol", "items": [
                "By the time we arrived, the film had started.",
                "She had just hung up when the doorbell rang.",
                "I had never seen such a crowd before that night.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Maya", "text": "What happened at the reunion?"},
                {"speaker": "You", "text": "I was standing by the window when I saw Tomas. We used to argue constantly at university. By the time I walked over, he had already left with someone."},
                {"speaker": "Maya", "text": "Did you use to get on at all?"},
                {"speaker": "You", "text": "On good days we would study together. I hadn't expected to feel that disappointed."},
            ], "ru": "фон continuous, used to, would, past perfect к моменту подхода."},
            {"type": "note", "text": "Частые ошибки: I was knowing (stative); After I had finished I had gone home без нужды в двух perfect; would be a teacher в значении used to be; I used to went; when I had arrived she cooked вместо by the time I arrived she had cooked (если еда раньше прихода). Не рисуйте весь абзац одним Past Simple, если есть фон и «ещё раньше»."},
            {"type": "note", "text": "Практика чтения в приложении продолжается книгой «A Scandal in Bohemia» (общественное достояние, Project Gutenberg) и graded readers: замечайте, как Конан Дойл чередует фон (was sitting) и факты (arrived) — это те же narrative tenses."},
            {"type": "h2", "text": "Говорение: 50 секунд — сцена из прошлого"},
            {"type": "p", "text": "Место + was/were + -ing, два Past Simple, одно Past Perfect, одно used to. Тема: первый день на работе / переезд / потерянный поезд."},
        ],
        [
            word("was-ing", "was/were + -ing", "фон в прошлом", "I was waiting outside."),
            word("had-v3", "had + V3", "раньше того прошлого", "She had left."),
            word("used-to", "used to", "раньше (привычка/состояние)", "I used to commute."),
            word("would-past", "would (past habit)", "бывало / имел обыкновение", "He would always arrive late."),
            word("by-the-time", "by the time", "к тому моменту как", "By the time we sat down…"),
            word("already", "already", "уже (к тому прошлому)", "had already gone"),
            word("did-you-use", "Did you use to…?", "ты раньше…?", "Did you use to smoke?"),
            word("realised", "realised", "понял(а)", "I realised I had forgotten."),
            word("standing", "standing", "стоял(а)", "I was standing by the door."),
            word("constantly", "constantly", "постоянно", "We used to argue constantly."),
            word("disappointed", "disappointed", "разочарованный", "I felt disappointed."),
            word("reunion", "reunion", "встреча выпускников / воссоединение", "a school reunion"),
        ],
        [
            ex("mcq", "I ____ TV when she called.", "was watching", ["watched", "was watching", "had watching", "have watched"], "прерывание → Past Continuous + when + Simple."),
            ex("mcq", "By the time we got there, they ____.", "had left", ["left already just now", "had left", "were leave", "have left"], "более раннее действие → Past Perfect."),
            ex("fill", "I ____ to live in York. (used)", "used", None, "used to live."),
            ex("fill", "Did you ____ to play tennis? (use)", "use", None, "Did you use to…?"),
            ex("tf", "«I would be shy as a child» — лучший выбор вместо used to be shy.", "false", ["true", "false"], "состояния — used to, не would."),
            ex("mcq", "On Sundays we ____ walk along the river. (привычка-воспоминание)", "would", ["are", "would", "have", "used"], "would + V1 для повторяющихся действий."),
            ex("fill", "She had ____ hung up. (just)", "just", None, "had just + V3."),
            ex("tf", "«I used to went there» — верная форма.", "false", ["true", "false"], "used to + V1: went нельзя."),
        ],
    ),
    lesson(
        "mixed-conditionals",
        {"en": "Mixed conditionals, unless, provided that, as long as", "ru": "Смешанные условные; unless, provided that, as long as"},
        22,
        {
            "en": "Combine 2nd and 3rd conditionals and limit them with unless, provided that, as long as.",
            "ru": "Второй, третий и mixed conditionals плюс unless / provided that / as long as — уверенная гипотеза на B2.",
        },
        [
            {"type": "p", "text": "Second — нереальное сейчас/будущее: If I had time, I would help. Third — нереальное прошлое: If I had had time, I would have helped. Mixed соединяет разные времена: прошлое условие → результат сейчас, или наоборот."},
            {"type": "h2", "text": "Карта условных"},
            {"type": "table", "headers": ["Тип", "If", "Главная", "Смысл"], "rows": [
                ["2nd", "Past Simple", "would + V1", "другое сейчас"],
                ["3rd", "Past Perfect", "would have + V3", "другое тогда"],
                ["mixed A", "had + V3", "would + V1", "прошлое → эффект сейчас"],
                ["mixed B", "Past Simple", "would have + V3", "характер/факт сейчас → прошлое"],
            ]},
            {"type": "pattern", "text": "If I had taken the job, I would be in Berlin now.     ·     If I weren't afraid of flying, I would have gone."},
            {"type": "example", "lang": "en", "en": "If I had slept more, I wouldn't be this tired now.", "ru": "mixed: прошлое условие, результат в настоящем. Скажите, подставив свою усталость."},
            {"type": "h3", "text": "unless / provided that / as long as"},
            {"type": "ul", "items": [
                "unless = if not: We'll go unless it rains. (не unless it will rain)",
                "provided (that) / providing (that) = только если (условие-допуск): You can borrow it provided that you bring it back.",
                "as long as = пока / при условии: I'll wait as long as you're honest.",
                "even if = даже если (уступка, не условие отмены): Even if I'm busy, I'll call.",
            ]},
            {"type": "h2", "text": "Инверсия (формальный регистр)"},
            {"type": "ol", "items": [
                "Had I known, I would have stayed. (= If I had known…)",
                "Were I you, I'd refuse. (редко, очень формально)",
                "Should you need help, call me. (= If you need… — вежливое будущее)",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Chris", "text": "We're stuck in this flat. If we had saved harder, we'd own a place by now."},
                {"speaker": "You", "text": "Unless we change jobs, we won't. I'd have applied last year if I weren't supporting my parents now."},
                {"speaker": "Chris", "text": "We can move provided that we keep a six-month buffer."},
                {"speaker": "You", "text": "As long as the rent stays reasonable, I'm in. Even if it's smaller."},
            ], "ru": "mixed (saved → own now), unless, provided that, as long as, even if."},
            {"type": "note", "text": "Частые ошибки: If I would have known (нужно If I had known); unless + not (двойное отрицание: unless you don't go — путаница); if I had went; mixed без логики времени (прошлое условие, а в главной will); provided to вместо provided that. would в if-части — почти всегда ошибка на этом уровне."},
            {"type": "note", "text": "Чтение: в «A Scandal in Bohemia» (Project Gutenberg, общественное достояние) и graded readers ищите гипотезы персонажей — даже если автор XIX века не рисует учебный mixed, вы можете пересказать сцену: If the King had been honest, he wouldn't be this anxious now."},
            {"type": "h2", "text": "Говорение: сожаление + настоящее"},
            {"type": "p", "text": "Две mixed-фразы про свою жизнь + одно unless и одно as long as про ближайший месяц. Без чтения с листа."},
        ],
        [
            word("would-have", "would have + V3", "сделал бы (прошлое)", "I would have called."),
            word("had-known", "If I had known", "если бы я знал(а) тогда", "If I had known, I'd have stayed."),
            word("unless", "unless", "если не", "unless it rains"),
            word("provided-that", "provided that", "при условии что", "provided that you pay"),
            word("as-long-as", "as long as", "пока / если только", "as long as you're honest"),
            word("even-if", "even if", "даже если", "even if I'm busy"),
            word("had-i-known", "Had I known…", "если бы я знал(а) — инверсия", "Had I known, I'd have waited."),
            word("buffer", "buffer", "подушка (финансы)", "a six-month buffer"),
            word("own", "own", "владеть", "we'd own a flat"),
            word("supporting", "supporting", "содержать / поддерживать", "supporting my parents"),
            word("reasonable", "reasonable", "разумный (о цене)", "reasonable rent"),
            word("mixed", "mixed conditional", "смешанный тип условного", "a mixed conditional"),
        ],
        [
            ex("mcq", "If I had taken the job, I ____ in Oslo now.", "would be", ["would have been always then", "would be", "will be", "am"], "прошлое условие → настоящее: would + V1."),
            ex("mcq", "We'll cancel ____ it snows heavily.", "if", ["unless", "if", "provided not", "as long"], "if it snows = отменим при снеге; unless it snows = отменим если НЕ пойдёт — читайте смысл."),
            ex("fill", "I would have gone if I ____ had time. (had)", "had", None, "If I had had time… — в задании нужен первый had: I would have gone if I had had time. Ожидается had."),
            ex("fill", "You can go ____ that you text me. (provided)", "provided", None, "provided that."),
            ex("tf", "«If I would have studied, I would have passed» — стандартный 3rd.", "false", ["true", "false"], "If I had studied, I would have passed."),
            ex("mcq", "____ I known, I would have helped.", "Had", ["If had", "Had", "Have", "Would"], "Had I known = If I had known."),
            ex("fill", "I'll wait as ____ as you try. (long)", "long", None, "as long as."),
            ex("tf", "«Unless it won't rain, we'll go» — естественный B2.", "false", ["true", "false"], "Unless it rains, we'll go. (без will в unless-части обычно)."),
        ],
    ),
    lesson(
        "reported-advanced",
        {"en": "Reporting verbs: suggest, warn, admit, deny, promise", "ru": "Глаголы пересказа: suggest, warn, admit, deny, promise"},
        20,
        {
            "en": "Go beyond say/tell: patterns after suggest, warn, admit, deny, promise and similar verbs.",
            "ru": "Дальше say/tell: модели после suggest, warn, admit, deny, promise — чтобы пересказывать точно.",
        },
        [
            {"type": "p", "text": "На B1 вы сдвигали времена после said/told. На B2 выбирают глагол с оттенком: не просто «сказала», а посоветовала, предупредила, признала, отрицала, пообещала. У каждого — своя модель: to-infinitive, -ing, that-clause, someone + that."},
            {"type": "h2", "text": "Сетка моделей"},
            {"type": "table", "headers": ["Глагол", "Типичная модель", "Пример"], "rows": [
                ["promise", "to + V1 / that", "She promised to call. / that she would call."],
                ["offer / refuse / agree", "to + V1", "He offered to help."],
                ["suggest / recommend / deny", "that + clause / -ing", "She suggested waiting. / that we wait."],
                ["admit / confess", "to + -ing / that", "He admitted stealing it. / that he had stolen it."],
                ["warn", "someone about / (not) to / that", "They warned us not to touch it."],
                ["accuse", "someone of + -ing", "She accused him of lying."],
                ["persuade / remind / force", "someone to + V1", "I persuaded her to stay."],
                ["insist", "on + -ing / that", "He insisted on paying."],
            ]},
            {"type": "pattern", "text": "suggest + -ing   ·   suggest that + подлежащее + (should) V1     ·     warn someone not to + V1"},
            {"type": "example", "lang": "en", "en": "He denied taking the file and promised to explain everything on Monday.", "ru": "denied + -ing, promised to. Произнесите — это язык отчёта на работе."},
            {"type": "h3", "text": "suggest без to me go"},
            {"type": "ul", "items": [
                "She suggested going by train. / She suggested that we (should) go by train.",
                "Не: She suggested me to go. (это смесь tell + suggest)",
                "advise: advise someone to + V1. recommend: recommend + -ing / that.",
            ]},
            {"type": "h2", "text": "Тон: смягчение пересказа"},
            {"type": "ol", "items": [
                "She claimed that… — она утверждала (вы не подтверждаете).",
                "He implied that… — намекнул, не сказал прямо.",
                "They allegedly… — по утверждениям (осторожный регистр новостей).",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Lead", "text": "What did the client say?"},
                {"speaker": "You", "text": "She complained that the invoice was late, accused us of ignoring emails, then admitted mixing up the PO number. She warned us not to miss the next deadline and asked us to promise to send a draft by Friday."},
                {"speaker": "Lead", "text": "Did she suggest a call?"},
                {"speaker": "You", "text": "Yes. She suggested speaking tomorrow morning and refused to wait until next week."},
            ], "ru": "цепочка reporting verbs в рабочем пересказе."},
            {"type": "note", "text": "Частые ошибки: suggest someone to; deny to do (обычно deny + -ing / that); explain me that (explain something to someone); tell to go без лица (tell someone to go); promise me going. Не ставьте that после каждого глагола автоматически — смотрите модель."},
            {"type": "note", "text": "В «A Scandal in Bohemia» и graded readers отмечайте, как персонажи передают чужие слова (the King said that… / he would not…). Перескажите абзац, заменив said на admitted, warned, promised — это тренировка B2, книга в общественном достоянии (Project Gutenberg)."},
            {"type": "h2", "text": "Говорение: минута-отчёт"},
            {"type": "p", "text": "Перескажите воображаемый конфликт соседей, минимум 5 разных reporting verbs. Не используйте said больше одного раза."},
        ],
        [
            word("suggest", "suggest + -ing / that", "предлагать", "She suggested waiting."),
            word("warn", "warn someone (not) to", "предупреждать", "They warned us not to go."),
            word("admit", "admit + -ing / that", "признавать", "He admitted lying."),
            word("deny", "deny + -ing / that", "отрицать", "She denied taking it."),
            word("promise", "promise to / that", "обещать", "I promised to write."),
            word("accuse", "accuse someone of", "обвинять в", "accused him of cheating"),
            word("persuade", "persuade someone to", "убедить сделать", "persuaded her to stay"),
            word("insist", "insist on", "настаивать на", "insisted on paying"),
            word("claim", "claim that", "утверждать (без вашей гарантии)", "She claimed that it was new."),
            word("imply", "imply that", "намекать / подразумевать", "He implied that we were late."),
            word("refuse", "refuse to", "отказываться", "refused to wait"),
            word("complain", "complain that / about", "жаловаться", "complained that it was late"),
        ],
        [
            ex("mcq", "She suggested ____ a lawyer.", "calling", ["to call me go", "calling", "me to calling", "call that"], "suggest + -ing."),
            ex("mcq", "They warned us ____ the cable.", "not to touch", ["to not touching", "not to touch", "don't touch that we", "not touching to"], "warn someone not to + V1."),
            ex("fill", "He denied ____ the money. (taking)", "taking", None, "deny + -ing."),
            ex("fill", "She accused him ____ lying. (of)", "of", None, "accuse someone of + -ing."),
            ex("tf", "«She suggested me to apply» — естественная модель suggest.", "false", ["true", "false"], "suggested applying / suggested that I apply."),
            ex("mcq", "He ____ to help with the boxes.", "offered", ["suggested", "offered", "denied", "accused"], "offer to + V1."),
            ex("fill", "I promised ____ email today. (to)", "to", None, "promise to + V1."),
            ex("tf", "После deny нормально «deny to steal».", "false", ["true", "false"], "deny stealing / deny that he stole."),
        ],
    ),
    lesson(
        "modal-deduction",
        {"en": "Modal deduction: must/might/can't have + V3", "ru": "Модальная дедукция: must/might/can't have + V3"},
        19,
        {
            "en": "Speculate about now and the past with must, might, can't and have + past participle.",
            "ru": "Догадки о настоящем и прошлом: must / might / can't и have + V3 — «должно быть», «не может быть».",
        },
        [
            {"type": "p", "text": "Модальные для дедукции — не обязанность, а оценка вероятности. Настоящее: must be (почти уверен), might/may/could be (возможно), can't be (почти исключено). Прошлое: must have + V3, might have + V3, can't have + V3. Это язык детектива и вежливого спора."},
            {"type": "h2", "text": "Сейчас vs тогда"},
            {"type": "table", "headers": ["Вероятность", "Настоящее", "Прошлое"], "rows": [
                ["~95% да", "She must be at work.", "She must have left early."],
                ["возможно", "She might be stuck.", "She might have missed the bus."],
                ["~95% нет", "She can't be in Paris — I saw her.", "She can't have seen the email yet."],
                ["логично ожидали, но нет", "should be here by now", "should have arrived by now"],
            ]},
            {"type": "pattern", "text": "must/might/can't + V1 (сейчас)     ·     must/might/can't + have + V3 (прошлое)"},
            {"type": "example", "lang": "en", "en": "The lights are off — they can't be at home. They must have gone out.", "ru": "can't be (сейчас) + must have gone (вывод о прошлом). Скажите обе фразы."},
            {"type": "h3", "text": "mustn't vs can't в дедукции"},
            {"type": "ul", "items": [
                "can't be — дедукция «невозможно, что это так».",
                "mustn't в британском чаще запрет, не дедукция (для дедукции прошлого — can't have, не mustn't have в учебном ядре B2).",
                "could have + V3 — могла произойти (и, возможно, не произошла): You could have been hurt.",
            ]},
            {"type": "h2", "text": "Тон в разговоре"},
            {"type": "ol", "items": [
                "I suppose… / I bet… — разговорные рамки рядом с might.",
                "There's no way she… ≈ she can't have…",
                "It looks as if / It seems… — смягчение вместо голого must.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Ravi", "text": "Lina isn't answering. She must be in the meeting."},
                {"speaker": "You", "text": "She can't be — she messaged two minutes ago. She might have put her phone on silent."},
                {"speaker": "Ravi", "text": "Then she should have seen my email. Unless she didn't go in to work?"},
                {"speaker": "You", "text": "She must have gone in. I saw her coat. She might not have checked her inbox yet."},
            ], "ru": "must be, can't be, might have, should have, must have gone."},
            {"type": "note", "text": "Частые ошибки: She must to be; She can have forgotten в значении «не может быть, что забыла» (нужно can't have forgotten); must как запрет и как дедукция без контекста; I must have been tired yesterday когда есть точный факт I was tired (дедукция — когда выводим, а не вспоминаем точно). could be ≠ could have been без временной оси."},
            {"type": "note", "text": "Читая «A Scandal in Bohemia» (Project Gutenberg) и graded readers, копируйте дедукцию Холмса учебными модальными: He must have recognised her. She can't have been the maid. Это мост от сюжета к вашей устной спекуляции."},
            {"type": "h2", "text": "Говорение: стол улик"},
            {"type": "p", "text": "Факты: мокрый зонт, пустая кружка, закрытый ноутбук. Сделайте 4 вывода: must / might / can't + одно have + V3."},
        ],
        [
            word("must-be", "must be", "должно быть (сейчас)", "She must be tired."),
            word("might-be", "might be", "может быть", "He might be late."),
            word("cant-be", "can't be", "не может быть (что так)", "It can't be true."),
            word("must-have", "must have + V3", "должно быть, сделал(а)", "must have forgotten"),
            word("might-have", "might have + V3", "возможно, сделал(а)", "might have missed it"),
            word("cant-have", "can't have + V3", "не может быть, что сделал(а)", "can't have seen it"),
            word("should-have", "should have + V3", "должен был (ожидание/упрёк)", "should have arrived"),
            word("could-have", "could have + V3", "мог(ло) бы случиться", "could have been worse"),
            word("suppose", "I suppose", "полагаю", "I suppose she's busy."),
            word("no-way", "There's no way…", "ни за что / не может быть", "There's no way she forgot."),
            word("silent", "on silent", "без звука (телефон)", "phone on silent"),
            word("inbox", "inbox", "входящие", "check her inbox"),
        ],
        [
            ex("mcq", "He's in a meeting — he ____ be answering.", "can't", ["must", "can't", "should to", "will must"], "логический запрет вывода: can't be answering / can't be available."),
            ex("mcq", "The window is open. Someone ____ left in a hurry.", "must have", ["must", "must have", "can't", "might to"], "вывод о прошлом: must have + V3."),
            ex("fill", "She might ____ missed the bus. (have)", "have", None, "might have + V3."),
            ex("fill", "They ____ have got the email yet. (can't)", "can't", None, "can't have + V3."),
            ex("tf", "«She must to be at home» — верно.", "false", ["true", "false"], "must be, без to."),
            ex("mcq", "Упрёк: You ____ told me.", "should have", ["must be", "should have", "can't be", "might to"], "should have + V3."),
            ex("fill", "He can't ____ seen it — he was in Rome. (have)", "have", None, "can't have + V3: He can't have seen it."),
            ex("tf", "Для дедукции «невозможно в прошлом» учебный стандарт B2 — mustn't have, а не can't have.", "false", ["true", "false"], "can't have + V3."),
        ],
    ),
    lesson(
        "advanced-passive",
        {"en": "Advanced passive: have/get something done, it is said that", "ru": "Продвинутый пассив: have/get something done, it is said that"},
        20,
        {
            "en": "Use causative have/get something done and impersonal reporting: it is said that / she is thought to.",
            "ru": "Каузатив have/get something done и безличный пересказ it is said that / she is thought to — речь и новости.",
        },
        [
            {"type": "p", "text": "Пассив B1: The report was written. На B2 нужны два расширения. Каузатив: I had my hair cut — услуга / кто-то сделал для вас (часто за деньги). Безличный репортаж: It is said that the minister will resign. / The minister is said to be considering it."},
            {"type": "h2", "text": "Have/get something done"},
            {"type": "table", "headers": ["Форма", "Оттенок", "Пример"], "rows": [
                ["have + object + V3", "нейтрально, заказали услугу", "I'm having the car serviced."],
                ["get + object + V3", "разговорнее / «удалось устроить»", "I got my phone fixed."],
                ["have something stolen", "каузатив-несчастье", "She had her bag stolen."],
                ["get someone to + V1", "уговорить человека", "I'll get him to call you."],
            ]},
            {"type": "pattern", "text": "have/get + вещь + V3     ·     не I cut my hair если парикмахер (тогда I had my hair cut)"},
            {"type": "example", "lang": "en", "en": "I need to get this document translated before Friday.", "ru": "Не сами переводите — заказываете. Произнесите как рабочую просьбу."},
            {"type": "h3", "text": "It is said that vs he is said to"},
            {"type": "ul", "items": [
                "It is said/thought/believed/reported that + clause.",
                "Someone is said/thought/believed to + V1 (сейчас/вообще).",
                "Someone is said to have + V3 (про прошлое): She is thought to have left the country.",
                "There is said to be… — существует, по слухам.",
            ]},
            {"type": "h2", "text": "Когда пассив уместен в речи"},
            {"type": "ol", "items": [
                "Деятель неизвестен или неважен: My laptop was stolen.",
                "Официальный тон: Applications must be submitted by noon.",
                "Не прячьте деятеля, если это вы отвечаете: лучше We made a mistake, чем Mistakes were made — если вас спросят прямо.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Noah", "text": "Why is the office closed?"},
                {"speaker": "You", "text": "We're having the alarms replaced. It is said that there was a false alert last night. The engineer is supposed to finish by four."},
                {"speaker": "Noah", "text": "Did you get the lock changed as well?"},
                {"speaker": "You", "text": "Not yet. I'll get someone to do it this week. Apparently a spare key is thought to have gone missing."},
            ], "ru": "having replaced, it is said that, get someone to, is thought to have."},
            {"type": "note", "text": "Частые ошибки: I cut my hair вчера в салоне (нужно I had it cut); I had cut my hair как каузатив (это Past Perfect «сам подстриг раньше»); It is said the minister без that в очень формальном письме лучше с that; He is said that he… (не смешивайте две схемы); by-фраза с I: The homework was done by me — часто неестественно."},
            {"type": "note", "text": "В «A Scandal in Bohemia» (общественное достояние, Gutenberg) и graded readers ловите пассив и слухи двора: it was said that the King… Перескажите абзац через is believed to have — не бросайте чтение ради одной грамматики."},
            {"type": "h2", "text": "Говорение: быт + новость"},
            {"type": "p", "text": "Три каузатива про дом/тело/технику + одна фраза it is said that про ваш город. Говорите, не читайте."},
        ],
        [
            word("have-done", "have something done", "сделать что-то (услуга)", "have the car washed"),
            word("get-done", "get something done", "сделать / починить (разг.)", "get it fixed"),
            word("serviced", "serviced", "прошедший ТО", "having the car serviced"),
            word("it-is-said", "It is said that…", "говорят, что…", "It is said that she's leaving."),
            word("is-said-to", "is said to", "якобы / считается что он(а)…", "He is said to be rich."),
            word("thought-to-have", "is thought to have + V3", "предположительно сделал(а)", "is thought to have left"),
            word("reported", "It is reported that", "сообщается, что", "It is reported that…"),
            word("supposed-to", "be supposed to", "предполагается / должен по плану", "He's supposed to finish at 4."),
            word("apparently", "apparently", "по всей видимости", "Apparently it's true."),
            word("replaced", "replaced", "заменён", "having the alarms replaced"),
            word("translated", "translated", "переведён", "get it translated"),
            word("missing", "gone missing", "пропал", "a key has gone missing"),
        ],
        [
            ex("mcq", "Парикмахер стриг вас вчера:", "I had my hair cut.", ["I cut my hair at the salon by me.", "I had my hair cut.", "I had cut my hair the salon.", "My hair cut me."], "have + object + V3."),
            ex("mcq", "Слухи: ____ that the factory will close.", "It is said", ["He is said that", "It is said", "They said to", "It says him"], "It is said that…"),
            ex("fill", "I'm having the boiler ____. (fixed)", "fixed", None, "having something V3."),
            ex("fill", "She is said ____ be in Rome. (to)", "to", None, "is said to + V1."),
            ex("tf", "«He is said that he is leaving» — смешение двух правильных схем, звучит стандартно.", "false", ["true", "false"], "It is said that he is leaving / He is said to be leaving."),
            ex("mcq", "Уговорю коллегу позвонить:", "I'll get him to call you.", ["I'll have him calling you to.", "I'll get him to call you.", "I'll get him call.", "I'll have get him call."], "get someone to + V1."),
            ex("fill", "They are thought to ____ fled. (have)", "have", None, "is thought to have + V3."),
            ex("tf", "«I had stolen my bike» как «у меня украли велосипед» — верный каузатив.", "false", ["true", "false"], "I had my bike stolen."),
        ],
    ),
    lesson(
        "emphasis-inversion",
        {"en": "Emphasis: so/such, clefts, negative inversion", "ru": "Эмфаза: so/such, cleft, инверсия после rarely/never"},
        21,
        {
            "en": "Add emphasis with so/such, it-clefts (it was X that) and inversion after rarely/never/not only.",
            "ru": "Усиление: so/such, it was X that…, инверсия после rarely / never / not only — чтобы звучать гибко, не только «very».",
        },
        [
            {"type": "p", "text": "B2-речь умеет выделять важное. so + adjective (+ that). such + (a/an) + noun. Cleft: It was the password that I forgot — не время, не человека, а пароль. Отрицательная инверсия: Never have I seen… — формально и сильно, не для каждого чата."},
            {"type": "h2", "text": "so / such"},
            {"type": "table", "headers": ["Схема", "Пример", "Ошибка"], "rows": [
                ["so + adj/adv", "The room was so cold that we left.", "so cold room"],
                ["such a/an + adj + noun", "It was such a cold room that we left.", "such cold room без a (ед. исчисл.)"],
                ["so much/many", "so much noise / so many emails", "so many noise"],
                ["such + uncount/plural", "such patience / such problems", "such a patience"],
            ]},
            {"type": "pattern", "text": "It was/is + выделяемое + that/who + остальное     ·     What I need is a break."},
            {"type": "example", "lang": "en", "en": "It was the last question that confused me, not the listening.", "ru": "cleft: вините вопрос, не аудирование. Скажите с ударением на last question."},
            {"type": "h3", "text": "Инверсия после отрицательных наречий"},
            {"type": "ul", "items": [
                "Never / Rarely / Seldom / Hardly / Not only / No sooner / Under no circumstances + вспомогательный + подлежащее.",
                "Never have I heard such nonsense.",
                "Not only did she apologise, but she also refunded us.",
                "No sooner had we sat down than the fire alarm went off. (had + V3, than)",
            ]},
            {"type": "h2", "text": "Разговорные усилители vs формальные"},
            {"type": "ol", "items": [
                "Разговор: I do want to help. (do/does/did + V1)",
                "Разговор: What on earth happened?",
                "Письмо/презентация: It is the cost that worries us. Rarely do we…",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Ivy", "text": "The meeting was such a waste of time."},
                {"speaker": "You", "text": "It was the lack of an agenda that annoyed me. Rarely have I seen people talk for an hour with no decision."},
                {"speaker": "Ivy", "text": "Not only were we unprepared, but we also ran over."},
                {"speaker": "You", "text": "What we need is a 15-minute stand-up, so short that nobody can hide."},
            ], "ru": "such a, cleft it was X that, rarely have I, not only were we, what we need is."},
            {"type": "note", "text": "Частые ошибки: such a good (без noun); so a nice day; Never I have seen; Not only she apologised без did; No sooner… when (нужно than); cleft It was I that в объекте — смотрите, что именно выделяете. Инверсию не ставьте в каждый ответ на small talk — это маркированный стиль."},
            {"type": "note", "text": "У Конан Дойла в «A Scandal in Bohemia» (Project Gutenberg) эмфаза часто идёт через лексику и ритм, не через учебную инверсию. Сверяйтесь с graded readers: найдите so/such и попробуйте переписать предложение как cleft — чтение плюс грамматика, не вместо."},
            {"type": "h2", "text": "Говорение: одна жалоба — три эмфазы"},
            {"type": "p", "text": "so/such + it-cleft + одна инверсия (rarely/never). Тема: ужасный звонок в поддержку. 35 секунд."},
        ],
        [
            word("so-that", "so + adj + that", "настолько … что", "so tired that I slept"),
            word("such-a", "such a + noun", "такой (вот) …", "such a mess"),
            word("cleft-it", "It was X that…", "именно X …", "It was Tom that called."),
            word("what-i-need", "What I need is…", "мне нужно именно…", "What I need is silence."),
            word("never-have", "Never have I…", "никогда я не… (инверсия)", "Never have I seen that."),
            word("rarely", "Rarely", "редко (часто с инверсией)", "Rarely do we agree."),
            word("not-only", "Not only… but also", "не только … но и", "Not only did he lie…"),
            word("no-sooner", "No sooner… than", "не успели … как", "No sooner had we left than…"),
            word("do-want", "I do want…", "я действительно хочу", "I do want to help."),
            word("agenda", "agenda", "повестка", "no agenda"),
            word("stand-up", "stand-up", "короткая летучка стоя", "a 15-minute stand-up"),
            word("ran-over", "run over (time)", "затянуться (о встрече)", "the meeting ran over"),
        ],
        [
            ex("mcq", "It was ____ a disaster that we stopped.", "such", ["so", "such", "too", "enough"], "such a + noun."),
            ex("mcq", "Never ____ I felt so awkward.", "have", ["I have", "have", "did have I never wait", "am"], "Never have I + V3."),
            ex("fill", "The soup was ____ hot that I couldn't eat it. (so)", "so", None, "so + adjective + that."),
            ex("fill", "It was the price ____ surprised us. (that)", "that", None, "cleft: It was X that…"),
            ex("tf", "«Never I have seen this» — правильная инверсия.", "false", ["true", "false"], "Never have I seen…"),
            ex("mcq", "Not only ____ she late, but she was also unprepared. (вспомогательный)", "was", ["did", "was", "has", "had she been only"], "Not only was she late… — be инвертируется само, без did."),
            ex("fill", "No sooner had we arrived ____ it started to rain. (than)", "than", None, "No sooner… than."),
            ex("tf", "«It was such a good weather» — правильная форма, потому что нужен артикль a.", "false", ["true", "false"], "weather неисчисляемое: such good weather (без a)."),
        ],
    ),
    lesson(
        "phrasal-collocations",
        {"en": "Phrasal verbs and collocations for B2 speech", "ru": "Фразовые глаголы и коллокации B2"},
        20,
        {
            "en": "High-frequency phrasal verbs plus collocations like make a decision and take responsibility.",
            "ru": "Частые phrasal verbs и коллокации make a decision, take responsibility — звучать «по-английски», не дословно с русского.",
        },
        [
            {"type": "p", "text": "На B2 вас выдаёт не артикль, а глагол+существительное. Русское «принять решение» — make a decision (не take a decision в американском ядре; BrE оба слышны, make безопаснее в курсе). «Нести ответственность» — take responsibility. Фразовые глаголы — отдельный словарь: look up, put off, bring up."},
            {"type": "h2", "text": "Рабочие фразовые"},
            {"type": "table", "headers": ["Phrasal", "Смысл", "Пример вслух"], "rows": [
                ["bring up", "поднять тему / воспитать", "Can I bring up the budget?"],
                ["put off", "отложить", "Don't put it off until Friday."],
                ["call off", "отменить", "They called off the meeting."],
                ["carry out", "выполнить (исследование/приказ)", "We carried out a survey."],
                ["come up with", "придумать", "She came up with a workaround."],
                ["look into", "разобраться (в проблеме)", "I'll look into it today."],
                ["turn down", "отклонить", "They turned down my offer."],
                ["work out", "получиться / рассчитать / тренироваться", "It didn't work out."],
            ]},
            {"type": "pattern", "text": "make a decision / a mistake / an effort / progress     ·     take responsibility / a break / notes / part     ·     do research / business (не make research)"},
            {"type": "example", "lang": "en", "en": "We need to make a decision today. I'll look into the costs and come up with two options.", "ru": "Три коллокации подряд — рабочий монолог. Произнесите без паузы на перевод."},
            {"type": "h3", "text": "Ещё якоря"},
            {"type": "ul", "items": [
                "pay attention (не give attention в этом значении).",
                "raise a concern / raise an issue (на собрании).",
                "keep someone posted — держать в курсе.",
                "run out of time/money/ideas.",
            ]},
            {"type": "h2", "text": "Отделяемые vs нет"},
            {"type": "ol", "items": [
                "put off the meeting / put the meeting off / put it off — местоимение только в середине.",
                "look after the kids — не look the kids after.",
                "Не угадывайте отделяемость — учите пример целиком.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Team", "text": "Shall we put the launch off?"},
                {"speaker": "You", "text": "I'd rather not. We have to take responsibility for the delay already. Let me look into the last bugs and come up with a timeline."},
                {"speaker": "Team", "text": "If legal turns us down, we'll have to call it off anyway."},
                {"speaker": "You", "text": "Then I'll bring it up with Marta. Keep me posted."},
            ], "ru": "put off, take responsibility, look into, come up with, turn down, call off, bring up, keep posted."},
            {"type": "note", "text": "Частые ошибки: make a research; take a decision как единственный вариант в US-контексте (часто make); discuss about; explain me; look the word (look the word up / look up the word); put off it (нужно put it off). Калька «провести время» — spend time, не conduct time."},
            {"type": "note", "text": "Пока учите коллокации, не забрасывайте чтение: «A Scandal in Bohemia» (Gutenberg, public domain) и graded readers дают естественные bring up / look into в контексте. Выписывайте глагол+дополнение, не одинокий глагол."},
            {"type": "h2", "text": "Говорение: статус на летучке"},
            {"type": "p", "text": "45 секунд: проблема, что вы look into, какой decision make, кого keep posted, что не put off. Минимум 4 выражения из урока."},
        ],
        [
            word("bring-up", "bring up", "поднять (тему)", "bring up the budget"),
            word("put-off", "put off", "отложить", "put it off"),
            word("call-off", "call off", "отменить (мероприятие)", "call off the launch"),
            word("look-into", "look into", "изучить / разобрать", "look into the costs"),
            word("come-up-with", "come up with", "предложить идею", "come up with options"),
            word("turn-down", "turn down", "отказать / отклонить", "turn down an offer"),
            word("make-a-decision", "make a decision", "принять решение", "make a decision today"),
            word("take-responsibility", "take responsibility", "взять ответственность", "take responsibility for the delay"),
            word("keep-posted", "keep me posted", "держи в курсе", "Keep me posted."),
            word("run-out", "run out of", "закончиться (запас)", "run out of time"),
            word("carry-out", "carry out", "выполнить (план/исследование)", "carry out a survey"),
            word("work-out", "work out", "получиться / решить", "It didn't work out."),
        ],
        [
            ex("mcq", "«Принять решение» в этом курсе:", "make a decision", ["do a decision", "make a decision", "create decision", "take decide"], "make a decision — безопасная коллокация."),
            ex("mcq", "Отложить запуск:", "put off the launch", ["put the launch of", "put off the launch", "off put launch", "make off the launch"], "put off + noun."),
            ex("fill", "I'll look ____ it. (into)", "into", None, "look into = разобраться."),
            ex("fill", "They turned ____ my application. (down)", "down", None, "turn down."),
            ex("tf", "«Put off it until Monday» — местоимение стоит правильно.", "false", ["true", "false"], "put it off."),
            ex("mcq", "Придумать решение:", "come up with a workaround", ["come up a workaround", "come up with a workaround", "come with up workaround", "make up with workaround always"], "come up with + idea."),
            ex("fill", "Please keep me ____. (posted)", "posted", None, "keep me posted."),
            ex("tf", "«Make a research» — стандартная коллокация.", "false", ["true", "false"], "do research."),
        ],
    ),
    lesson(
        "hedging-register",
        {"en": "Hedging and register: emails vs speech", "ru": "Хеджирование и регистр: письмо и разговор"},
        21,
        {
            "en": "Soften claims with might, seem, tend to, and switch between formal and informal email and speech.",
            "ru": "Смягчать утверждения: might, seem, tend to; формальный и неформальный регистр в письме и устной речи.",
        },
        [
            {"type": "p", "text": "B2-независимый пользователь не долбит фактами, если не уверен. Hedging — might, seem, appear, tend to, it could be argued, as far as I know. Регистр: Hi Tom vs Dear Ms Khan; Can you send vs I would be grateful if you could send."},
            {"type": "h2", "text": "Смягчители"},
            {"type": "table", "headers": ["Прямо (резко)", "Смягчено", "Когда"], "rows": [
                ["You're wrong.", "I might be missing something, but…", "несогласие"],
                ["This is a bad idea.", "This seems a little rushed.", "оценка"],
                ["People always do X.", "People tend to do X.", "обобщение"],
                ["It will fail.", "It may not work in every case.", "прогноз"],
                ["Send the file.", "When you have a moment, could you send the file?", "просьба"],
            ]},
            {"type": "pattern", "text": "It seems (that)…     ·     It tends to + V1     ·     I would be grateful if you could + V1"},
            {"type": "example", "lang": "en", "en": "I might be wrong, but the figures seem a bit high. Could we double-check?", "ru": "hedge + seem + вежливая просьба. Произнесите на совещании, не извиняясь за само существование."},
            {"type": "h3", "text": "Письмо: два полюса"},
            {"type": "ul", "items": [
                "Неформально: Hi, thanks, I'll ping you, Cheers.",
                "Нейтрально-работа: Hi Anna, Just a quick note to… Best regards.",
                "Формально: Dear Sir or Madam, I am writing to enquire… Yours faithfully (если нет имени) / Yours sincerely (есть имя).",
            ]},
            {"type": "h2", "text": "Ложные друзья регистра"},
            {"type": "ol", "items": [
                "В письме боссу «Hey you, send ASAP!!!» ломает тон сильнее, чем одна грамматическая ошибка.",
                "В пабе Dear Sir звучит шуткой или холодом.",
                "too much hedging («I kind of maybe think perhaps») — неуверенность, не вежливость.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "You", "text": "Hi Priya — just a quick note. The timeline seems tight. We might need an extra day. Would you be able to confirm by Thursday?"},
                {"speaker": "Priya", "text": "Thanks for flagging that. I tend to agree. I'll check with legal. Speak soon."},
                {"speaker": "You", "text": "(later, to a friend) Yeah, the deadline's insane. I told her it might slip."},
            ], "ru": "один смысл — два регистра: письмо коллеге и разговор с другом."},
            {"type": "note", "text": "Частые ошибки: I am writing for to ask; looking forward to hear (hearing); Yours faithfully с именем в Dear; might to go; people is tend to. Смягчение не заменяет ясности: после hedge скажите, что именно нужно сделать."},
            {"type": "note", "text": "Регистр XIX века в «A Scandal in Bohemia» (Project Gutenberg) формальнее Slack. Читайте книгу и graded readers как музей тона, а письма в приложении пишите современным B2: вежливо, коротко, с hedge где нет пруфов."},
            {"type": "h2", "text": "Говорение: одна новость — два тона"},
            {"type": "p", "text": "Сообщите, что дедлайн, кажется, сорвётся: 1) другу, 2) клиенту по телефону. Сравните слова. Запишите оба дубля."},
        ],
        [
            word("might", "might", "возможно (смягчение)", "We might need a day."),
            word("seem", "seem", "казаться", "It seems tight."),
            word("tend-to", "tend to", "как правило", "I tend to agree."),
            word("as-far-as", "as far as I know", "насколько мне известно", "As far as I know, it's done."),
            word("grateful", "I would be grateful if…", "был(а) бы признателен(льна), если…", "I would be grateful if you could send it."),
            word("enquire", "enquire (BrE)", "справляться (формально)", "I am writing to enquire…"),
            word("sincerely", "Yours sincerely", "с уважением (имя известно)", "Yours sincerely,"),
            word("faithfully", "Yours faithfully", "с уважением (имени нет)", "Yours faithfully,"),
            word("flagging", "flag something", "отметить проблему", "Thanks for flagging that."),
            word("ping", "ping someone", "написать коротко (неформ.)", "I'll ping you."),
            word("insane", "insane (informal)", "безумный (разг.)", "The deadline's insane."),
            word("double-check", "double-check", "перепроверить", "Could we double-check?"),
        ],
        [
            ex("mcq", "Формальная просьба прислать файл:", "I would be grateful if you could send the file.", ["Send file now.", "I would be grateful if you could send the file.", "You must sending the file.", "Hey dump the file."], "would be grateful if you could + V1."),
            ex("mcq", "Обобщение мягче always:", "People tend to reply late on Fridays.", ["People always never reply.", "People tend to reply late on Fridays.", "People is reply late.", "People must reply late always fact."], "tend to + V1."),
            ex("fill", "It ____ a bit rushed. (seems)", "seems", None, "seems + adjective."),
            ex("fill", "Yours ____, — если в обращении есть имя (sincerely)", "sincerely", None, "Dear Ms Khan → Yours sincerely."),
            ex("tf", "«Looking forward to hear from you» — верный герундий после to-предлога.", "false", ["true", "false"], "looking forward to hearing."),
            ex("mcq", "Нет имени получателя в Dear:", "Yours faithfully", ["Yours sincerely only always", "Yours faithfully", "Cheers mate", "Bestie regards"], "Dear Sir or Madam → Yours faithfully."),
            ex("fill", "We ____ need extra time. (might)", "might", None, "might + V1."),
            ex("tf", "Чем больше kind of maybe perhaps подряд, тем вежливее и яснее B2.", "false", ["true", "false"], "Один-два hedge + конкретная просьба."),
        ],
    ),
    lesson(
        "discourse-essay",
        {"en": "Discourse markers: essays vs spoken fillers", "ru": "Дискурс: however, on the one hand; заполнители речи"},
        20,
        {
            "en": "Use however, nevertheless, on the one hand, in conclusion — and drop empty spoken fillers.",
            "ru": "Письменные маркеры however / nevertheless / on the one hand / in conclusion и устные: какие fillers мешают, какие помогают.",
        },
        [
            {"type": "p", "text": "Эссе и устный монолог B2 держатся на знаках поворота мысли. however / nevertheless — противопоставление после точки. on the one hand / on the other hand — две стороны (не растягивайте на минуту). in conclusion / to sum up — финал. В речи те же функции часто короче: but, still, so, anyway."},
            {"type": "h2", "text": "Письменная сетка"},
            {"type": "table", "headers": ["Функция", "Маркер", "Не делайте"], "rows": [
                ["добавить", "moreover, in addition, furthermore", "три furthermore в одном абзаце"],
                ["противопоставить", "however, nevertheless, even so", "However в середине без пунктуации как but"],
                ["две стороны", "on the one hand… on the other hand", "забыть вторую руку"],
                ["пример", "for instance, for example", "example like as such"],
                ["вывод", "therefore, as a result, consequently", "so в начале каждого предложения письма"],
                ["конец", "in conclusion, to sum up, overall", "In conclusion repeating the title only"],
            ]},
            {"type": "pattern", "text": "On the one hand, + clause. On the other hand, + clause.     ·     Nevertheless, + clause."},
            {"type": "example", "lang": "en", "en": "Remote work is flexible. Nevertheless, some teams lose speed. Overall, a hybrid model seems safer.", "ru": "факт — nevertheless — overall. Проговорите как 15-секундное мини-эссе."},
            {"type": "h3", "text": "Fillers: вредные и полезные"},
            {"type": "ul", "items": [
                "Мешают, если ими заполняют пустоту каждые три слова: um, uh, like, you know, kinda.",
                "Полезны как стратегии ремонта: Let me rephrase that. What I mean is… The point is… Hang on — the word I want is…",
                "Пауза молчанием лучше, чем like-like-like.",
            ]},
            {"type": "h2", "text": "Устный монолог без «эссе вслух»"},
            {"type": "ol", "items": [
                "Начните с позиции: I think / I'm in favour of…",
                "Один however достаточно.",
                "Закончите so, basically… только если резюмируете, не извиняетесь.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Examiner", "text": "Should cities ban cars from the centre?"},
                {"speaker": "You", "text": "On the one hand, air quality would improve. On the other hand, small shops might suffer. What I mean is, deliveries still need access. Nevertheless, I'd support a limited ban. So, overall, yes — with exceptions."},
            ], "ru": "две руки, what I mean is, nevertheless, overall — устный дискурс B2."},
            {"type": "note", "text": "Частые ошибки: on the one hand без other; In conclusion в середине; however, but подряд; moreover = but по смыслу (нет); письменные furthermore в разговоре с друзьями. At first vs firstly (at first = сначала казалось; firstly = пункт 1)."},
            {"type": "note", "text": "Стиль «A Scandal in Bohemia» (Project Gutenberg) — литературный дискурс XIX века. Для экзаменационного эссе берите современные связки из этого урока; книгу и graded readers используйте как чтение, не как шаблон абзаца IELTS."},
            {"type": "h2", "text": "Говорение: 40 секунд без um"},
            {"type": "p", "text": "Тема на выбор: соцсети / офис / спорт. Каркас: позиция — on the one hand — on the other — nevertheless — overall. Если зависли: What I mean is… и проще."},
        ],
        [
            word("however", "however", "однако (часто новое предл.)", "However, costs rose."),
            word("nevertheless", "nevertheless", "тем не менее", "Nevertheless, I'd support it."),
            word("on-the-one-hand", "on the one hand", "с одной стороны", "On the one hand, it's cheaper."),
            word("on-the-other", "on the other hand", "с другой стороны", "On the other hand, it's slower."),
            word("in-conclusion", "in conclusion", "в заключение", "In conclusion, I agree."),
            word("overall", "overall", "в целом", "Overall, it's safer."),
            word("moreover", "moreover", "кроме того (письмо)", "Moreover, staff agree."),
            word("therefore", "therefore", "следовательно", "Therefore, we waited."),
            word("what-i-mean", "What I mean is…", "я имею в виду…", "What I mean is, we need time."),
            word("rephrase", "Let me rephrase that", "скажу иначе", "Let me rephrase that."),
            word("for-instance", "for instance", "например", "for instance, deliveries"),
            word("in-favour", "in favour of (BrE)", "за (идею)", "I'm in favour of a ban."),
        ],
        [
            ex("mcq", "С одной стороны:", "On the one hand", ["In the one hand", "On the one hand", "To one side hand", "On one the hand"], "On the one hand…"),
            ex("mcq", "Сильнее however в начале:", "Nevertheless,", ["And but,", "Nevertheless,", "Like so,", "Um,"], "Nevertheless + запятая + клауза."),
            ex("fill", "In ____, the policy works. (conclusion)", "conclusion", None, "In conclusion."),
            ex("fill", "What I ____ is we need data. (mean)", "mean", None, "What I mean is…"),
            ex("tf", "«On the one hand» можно оставить без «on the other hand» и звучать завершённо.", "false", ["true", "false"], "Слушатель ждёт вторую сторону или вы сознательно обрываете — на экзамене закройте пару."),
            ex("mcq", "Полезный repair, не пустой like:", "Let me rephrase that.", ["like, like, you know", "Let me rephrase that.", "um um um", "kinda sorta"], "Let me rephrase that / What I mean is…"),
            ex("fill", "____, I support hybrid work. (Overall)", "Overall", None, "Overall как вывод."),
            ex("tf", "Furthermore каждые два предложения улучшает устный ответ другу.", "false", ["true", "false"], "Furthermore — письменный регистр; в речи достаточно also / besides / plus."),
        ],
    ),
    lesson(
        "wish-regret",
        {"en": "Wish, if only, it's time, would rather", "ru": "Wish, if only, it's time, would rather"},
        19,
        {
            "en": "Express regret and preference: wish + past, if only, it's time, would rather.",
            "ru": "Сожаление и предпочтение: wish + прошедшее, if only, it's time, would rather — живая B2-эмоция, не только грамматика.",
        },
        [
            {"type": "p", "text": "wish не про день рождения. I wish + Past Simple — другое настоящее: I wish I knew. I wish + Past Perfect — сожаление о прошлом: I wish I had known. I wish + would — раздражение на чужое повторяющееся поведение: I wish you would knock. Это сосед second/third conditional, но без if."},
            {"type": "h2", "text": "Четыре конструкции"},
            {"type": "table", "headers": ["Формула", "Смысл", "Пример"], "rows": [
                ["wish + Past Simple", "хочу, чтобы сейчас было иначе", "I wish I spoke French."],
                ["wish + Past Perfect", "жаль, что тогда", "I wish I hadn't sent that email."],
                ["wish + would (+ not)", "пусть бы ты перестал/начал (чужая воля)", "I wish it would stop raining."],
                ["if only", "то же, сильнее эмоционально", "If only we had left earlier."],
            ]},
            {"type": "pattern", "text": "It's time + Past Simple (пора уже)     ·     would rather + V1 (сам)     ·     would rather someone + Past Simple"},
            {"type": "example", "lang": "en", "en": "I wish I hadn't agreed so quickly. It's time we set clearer limits.", "ru": "сожаление о прошлом + it's time + Past. Скажите как взрослый разговор, не как упражнение."},
            {"type": "h3", "text": "it's time / would rather / I'd prefer"},
            {"type": "ul", "items": [
                "It's time we left. (Past по форме, смысл «уже пора сейчас»). It's time to leave — проще, тоже верно.",
                "I'd rather stay in. I'd rather you stayed in. (не would rather you to stay)",
                "I'd prefer to wait / I'd prefer it if you waited.",
            ]},
            {"type": "h2", "text": "Чего wish не делает"},
            {"type": "ol", "items": [
                "I wish I would be taller — про своё состояние лучше I wish I were taller (were снова уместен).",
                "I wish I will… — нет, это hope: I hope you will…",
                "hope — реальное будущее; wish — контрфакт или раздражение.",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Dana", "text": "If only the neighbours would turn the music down."},
                {"speaker": "You", "text": "I wish they'd bought a house elsewhere. It's time we spoke to them. I'd rather you started the conversation — you're calmer."},
                {"speaker": "Dana", "text": "I wish I were calmer. Fine. I'd rather not argue in the hallway, though."},
                {"speaker": "You", "text": "I wish I hadn't promised to deal with it alone last time."},
            ], "ru": "wish would, wish past perfect, it's time, would rather you, wish I were, wish I hadn't."},
            {"type": "note", "text": "Частые ошибки: I wish I know; I wish I would live in Spain про своё постоянное желание (I wish I lived); I wish you to stop; It's time we go вместо went в «уже давно пора»; would rather + to. if only that I — лишнее that часто не нужно."},
            {"type": "note", "text": "Сожаления короля в «A Scandal in Bohemia» (общественное достояние, Project Gutenberg) легко переложить на wish: He wishes he had never written the letters. Держите graded readers открытыми — эмоция + конструкция запоминаются вместе."},
            {"type": "h2", "text": "Говорение: три жали"},
            {"type": "p", "text": "Одно wish про сейчас, одно про прошлое, одно wish you would. Добавьте it's time we… Не читайте список — смотрите в окно."},
        ],
        [
            word("wish-knew", "I wish I knew", "жаль, что не знаю (сейчас)", "I wish I knew the answer."),
            word("wish-had", "I wish I had + V3", "жаль, что не сделал(а) тогда", "I wish I had left."),
            word("wish-would", "I wish you would…", "сделал бы ты уже…", "I wish you would listen."),
            word("if-only", "if only", "если бы только", "If only we'd waited."),
            word("its-time", "It's time + Past", "уже пора", "It's time we left."),
            word("would-rather", "would rather", "предпочёл(а) бы", "I'd rather stay."),
            word("were", "I wish I were", "хотел(а) бы быть (were)", "I wish I were taller."),
            word("hadn't", "I wish I hadn't", "жаль, что сделал(а)", "I wish I hadn't agreed."),
            word("hope", "hope", "надеюсь (реальное)", "I hope you pass."),
            word("prefer", "would prefer", "предпочёл(а) бы", "I'd prefer to wait."),
            word("calmer", "calmer", "спокойнее", "you're calmer"),
            word("limits", "limits", "границы / рамки", "set clearer limits"),
        ],
        [
            ex("mcq", "Жаль, что не умею (сейчас):", "I wish I spoke Italian.", ["I wish I speak Italian.", "I wish I spoke Italian.", "I wish I will speak Italian.", "I wish I would speaking Italian."], "wish + Past Simple про настоящее."),
            ex("mcq", "Сожаление о письме:", "I wish I hadn't sent it.", ["I wish I didn't sent it yesterday grammar mix.", "I wish I hadn't sent it.", "I wish I wouldn't sent it.", "I wish not send it."], "wish + Past Perfect."),
            ex("fill", "It's time we ____. (left)", "left", None, "It's time + Past Simple."),
            ex("fill", "I'd rather you ____. (stayed)", "stayed", None, "would rather + person + Past."),
            ex("tf", "«I wish I will be rich» — стандартный wish.", "false", ["true", "false"], "I wish I were rich / I hope I will be…"),
            ex("mcq", "Раздражение на шум:", "I wish they would be quiet.", ["I wish they are quiet now fact.", "I wish they would be quiet.", "I wish they have been quiet always known.", "I hope they would be quiet mixed."], "wish + would — чужое поведение."),
            ex("fill", "If ____ I had listened. (only)", "only", None, "If only…"),
            ex("tf", "«I'd rather to go home» — верная форма.", "false", ["true", "false"], "I'd rather go home."),
        ],
    ),
    lesson(
        "b2-debate",
        {"en": "B2 debate: agree, concede, challenge, speculate", "ru": "B2 дебаты: согласие, уступка, вызов, причины"},
        22,
        {
            "en": "Agree, concede, challenge and speculate about causes in a discussion.",
            "ru": "Соглашаться, уступать, оспаривать и гадать о причинах — дискуссия независимого пользователя B2.",
        },
        [
            {"type": "p", "text": "Дебаты B2 — не крик. Вы держите свою линию, признаёте сильный аргумент оппонента и возвращаетесь с however / even so. Спекуляция о причинах: it might be because, one possible explanation is, this could be down to…"},
            {"type": "h2", "text": "Реплики-роли"},
            {"type": "table", "headers": ["Ход", "Фразы", "Зачем"], "rows": [
                ["согласиться", "I agree up to a point. That's fair.", "не всё или ничего"],
                ["уступить", "I'll grant you that… / Fair enough, but…", "показать, что слышите"],
                ["оспорить", "I'm not convinced. Where's the evidence?", "требовать опору"],
                ["уточнить", "Are you saying that…? If I understand you…", "не атаковать соломенное чучело"],
                ["причины", "This might be due to… / It could stem from…", "спекуляция, не догма"],
                ["вернуть мяч", "Even so, the main issue remains…", "после уступки"],
            ]},
            {"type": "pattern", "text": "I'll grant you X. Even so, Y.     ·     One possible explanation is that…"},
            {"type": "example", "lang": "en", "en": "I'll grant you that housing is expensive. Even so, I'm not convinced that rent caps are the whole solution.", "ru": "уступка + even so + сомнение. Это фраза, которую стоит сказать вслух до дебатов."},
            {"type": "h3", "text": "Спекуляция о причинах"},
            {"type": "ul", "items": [
                "This could be down to funding / habit / fear of change.",
                "It may have something to do with…",
                "We can't say for sure, but…",
                "Correlation isn't causation — осторожно с because после одного графика.",
            ]},
            {"type": "h2", "text": "Правила вежливости"},
            {"type": "ol", "items": [
                "Не перебивайте середину клаузы — wait for a beat, then Can I come in here?",
                "Атакуйте идею, не человека: That argument overlooks… не You're naïve.",
                "Если не знаете факт: I don't have the figures to hand, but my impression is…",
            ]},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "Leila", "text": "Shorter working weeks would kill productivity."},
                {"speaker": "You", "text": "I agree up to a point — some roles need coverage. I'll grant you that hospitals can't all close on Fridays. Even so, I'm not convinced office work would collapse. It might be due to meetings, not hours."},
                {"speaker": "Leila", "text": "Where's the evidence?"},
                {"speaker": "You", "text": "Fair question. We can't say for sure. One possible explanation is burnout. Can we look at a trial rather than a nationwide jump?"},
            ], "ru": "согласие частично, grant you, even so, due to, evidence, possible explanation."},
            {"type": "note", "text": "Частые ошибки: I am agree; You don't understand nothing; because why (по-русски «потому что почему»); concede и сразу повтор того же без even so; must как единственная причина (It must be laziness) без might. Challenging ≠ interrupting every five seconds."},
            {"type": "note", "text": "Споры о репутации и письмах в «A Scandal in Bohemia» (Gutenberg) — готовый материал для дебата: should the King have confessed earlier? Сформулируйте устно grant you / even so, затем вернитесь к graded readers за лексикой эпохи, не за криком."},
            {"type": "h2", "text": "Говорение: 90 секунд на двоих"},
            {"type": "p", "text": "Тема: «Нужно ли запретить телефоны в школах?» Каждый: 1 согласие, 1 уступка, 1 вызов where's the evidence, 1 спекуляция might be due to. Без личных оскорблений."},
        ],
        [
            word("up-to-a-point", "up to a point", "отчасти", "I agree up to a point."),
            word("grant-you", "I'll grant you that", "признаю, что", "I'll grant you that it's costly."),
            word("even-so", "even so", "и всё же", "Even so, I disagree."),
            word("not-convinced", "I'm not convinced", "меня не убедили", "I'm not convinced."),
            word("due-to", "due to", "из-за (часто noun)", "due to meetings"),
            word("stem-from", "stem from", "происходить от", "problems stem from fear"),
            word("to-hand", "to hand", "под рукой (данные)", "I don't have the figures to hand."),
            word("come-in", "Can I come in here?", "можно вставить реплику?", "Can I come in here?"),
            word("overlooks", "overlook", "упускать из виду", "That argument overlooks cost."),
            word("trial", "trial", "пилотный запуск / испытание", "look at a trial"),
            word("burnout", "burnout", "выгорание", "due to burnout"),
            word("fair-enough", "Fair enough", "справедливо / ладно", "Fair enough, but…"),
        ],
        [
            ex("mcq", "Частичное согласие:", "I agree up to a point.", ["I am agree totally silent.", "I agree up to a point.", "You stupid idea.", "Yes no always."], "up to a point оставляет пространство для however."),
            ex("mcq", "После уступки вернуть позицию:", "Even so, the main issue remains.", ["Even so, the main issue remains.", "So you lose.", "Because why you.", "I grant nothing ever."], "Even so + ваша линия."),
            ex("fill", "I'll ____ you that it's expensive. (grant)", "grant", None, "I'll grant you that…"),
            ex("fill", "This might be ____ to funding. (due)", "due", None, "due to + noun."),
            ex("tf", "«I'm not convinced» грубее, чем «You're an idiot».", "false", ["true", "false"], "I'm not convinced — стандартный вежливый вызов."),
            ex("mcq", "Спекуляция, не догма:", "One possible explanation is burnout.", ["It is laziness period fact.", "One possible explanation is burnout.", "Must because people bad.", "The because is."], "possible explanation / might be due to."),
            ex("fill", "Can I ____ in here? (come)", "come", None, "Can I come in here?"),
            ex("tf", "На B2 достаточно кричать громче оппонента — маркеры уступки не нужны.", "false", ["true", "false"], "Независимый пользователь умеет concede и затем even so."),
        ],
    ),
    lesson(
        "b2-fluency-lab",
        {"en": "B2 fluency lab: meeting, GP visit, news, repair", "ru": "B2 лаборатория: совещание, врач, новости, ремонт фразы"},
        22,
        {
            "en": "Speak through a work meeting, a non-jargon doctor's visit and a news chat, using repair: what I mean is…",
            "ru": "Совещание, визит к врачу без жаргона, разговор о новостях и стратегии ремонта: what I mean is… — беглость независимого пользователя.",
        },
        [
            {"type": "p", "text": "Лаборатория собирает курс: времена рассказа, hedge, пассив слухов, дедукция, вежливый конфликт. Цель CEFR B2 — связать речь, исправить себя и не замолкать. Три сцены + ящик с инструментами ремонта."},
            {"type": "h2", "text": "Сцена 1 — рабочее совещание"},
            {"type": "table", "headers": ["Шаг", "Фраза", "Зачем"], "rows": [
                ["открыть пункт", "Can we take the budget first?", "повестка"],
                ["статус", "We've looked into it; it turns out the delay was on their side.", "факт + hedge-точность"],
                ["предложение", "I'd suggest pushing the date rather than rushing the test.", "suggest + -ing"],
                ["несогласие", "I take your point. Even so, we can't skip QA.", "уступка"],
                ["действие", "I'll take responsibility for the email to the client.", "коллокация"],
                ["закрыть", "So, to recap: we delay by a week. Agreed?"],
            ]},
            {"type": "example", "lang": "en", "en": "I take your point about speed. Even so, I'd rather we didn't skip the test. What I mean is, a bug in production would cost more.", "ru": "уступка + would rather + repair. Скажите это как на настоящем созвоне."},
            {"type": "h2", "text": "Сцена 2 — к врачу (без медицинского жаргона)"},
            {"type": "dialogue", "lang": "en", "lines": [
                {"speaker": "GP", "text": "What brings you in today?"},
                {"speaker": "You", "text": "I've been getting headaches for two weeks. They tend to start in the afternoon. I thought it might be screens, but it hasn't let up."},
                {"speaker": "GP", "text": "Any other symptoms?"},
                {"speaker": "You", "text": "I feel sick sometimes. I'm not allergic to anything I know of. I'd rather avoid strong painkillers if we can."},
                {"speaker": "GP", "text": "We'll start with rest and a check of your blood pressure. If it hasn't improved in a week, come back."},
            ], "ru": "симптомы простым языком, tend to, might, would rather avoid."},
            {"type": "h3", "text": "Сцена 3 — новости"},
            {"type": "ul", "items": [
                "Have you seen the story about…?",
                "Apparently / It's been reported that… — не клянитесь, если не читали первоисточник.",
                "It could be a coincidence. We shouldn't jump to conclusions.",
                "What do you make of it?",
            ]},
            {"type": "h2", "text": "Repair strategies"},
            {"type": "ol", "items": [
                "What I mean is… / In other words…",
                "Sorry, that came out wrong.",
                "The word has slipped my mind. It's like…",
                "Let me start again.",
                "Am I making sense?",
            ]},
            {"type": "note", "text": "Частые ошибки беглости: бросать фразу на середине без repair; извиняться за акцент вместо уточнения смысла; перегружать jargon у врача; на совещании только I think I think I think; в новостях must как единственный вывод. Тишина 1 секунда + What I mean is лучше, чем ложный термин."},
            {"type": "note", "text": "Финальный мост к чтению: продолжайте «A Scandal in Bohemia» (общественное достояние, Project Gutenberg) и graded readers параллельно с этой лабораторией. Перескажите сцену Холмса языком совещания: to recap, apparently, what I mean is — так грамматика B2 садится в голос."},
            {"type": "h2", "text": "Зачёт голосом"},
            {"type": "p", "text": "Запишите три дубля по 40 секунд: совещание, врач, новость. В каждом минимум один repair (what I mean is / let me rephrase). Прослушайте: где вы ускорились так, что пропало окончание -ed? Повторите только это предложение."},
        ],
        [
            word("take-your-point", "I take your point", "понимаю твой аргумент", "I take your point."),
            word("to-recap", "to recap", "подводя итог", "So, to recap…"),
            word("turns-out", "it turns out", "оказывается", "It turns out they delayed."),
            word("qa", "QA / testing", "проверка качества", "we can't skip QA"),
            word("what-brings", "What brings you in?", "что привело (к врачу)?", "What brings you in today?"),
            word("let-up", "let up", "ослабеть (о боли/дожде)", "It hasn't let up."),
            word("painkillers", "painkillers", "обезболивающие", "avoid strong painkillers"),
            word("apparently", "apparently", "как сообщается / видимо", "Apparently it's delayed."),
            word("make-of", "What do you make of it?", "что об этом думаешь?", "What do you make of it?"),
            word("came-out-wrong", "that came out wrong", "не так выразился/лась", "Sorry, that came out wrong."),
            word("slipped-mind", "slipped my mind", "вылетело из головы", "The word has slipped my mind."),
            word("making-sense", "Am I making sense?", "я понятно объясняю?", "Am I making sense?"),
            word("jump-conclusions", "jump to conclusions", "спешить с выводами", "Don't jump to conclusions."),
        ],
        [
            ex("mcq", "Ремонт фразы:", "What I mean is, we need more time.", ["Forget English I stupid.", "What I mean is, we need more time.", "Blah blah you know like.", "Silence forever."], "What I mean is + проще."),
            ex("mcq", "Итог совещания:", "So, to recap, we delay by a week.", ["So recap we delay week yes no.", "So, to recap, we delay by a week.", "Finish talk go.", "Agenda die."], "to recap + решение."),
            ex("fill", "I take your ____. (point)", "point", None, "I take your point."),
            ex("fill", "What ____ you in today? (brings)", "brings", None, "What brings you in?"),
            ex("tf", "У врача B2 обязан использовать латинские термины, иначе уровень «ниже».", "false", ["true", "false"], "Независимый пользователь объясняет симптомы простыми словами."),
            ex("mcq", "Новости без догмы:", "Apparently the vote has been delayed.", ["Must be conspiracy I know.", "Apparently the vote has been delayed.", "It fact definitely I saw dream.", "They always evil."], "Apparently / It's been reported that…"),
            ex("fill", "The word has ____ my mind. (slipped)", "slipped", None, "slipped my mind."),
            ex("tf", "«That came out wrong» — полезная стратегия ремонта, не признание, что вы «плохой ученик».", "true", ["true", "false"], "Так носители поправляют тон, не личность."),
            ex("mcq", "I'd rather we ____ skip the test.", "didn't", ["don't to", "didn't", "not", "aren't"], "would rather + subject + Past: I'd rather we didn't skip…"),
        ],
    ),
]
