def _ex(kind, prompt, answer, options=None, explanation=""):
    item = {"type": kind, "prompt": prompt, "answer": answer, "explanation": explanation}
    if options:
        item["options"] = options
    return item


def _word(wid, front, back, example=""):
    return {"id": wid, "front": front, "back": back, "example": example}


def _lesson(slug, title, minutes, summary, sections, vocab, exercises):
    return {
        "slug": slug,
        "title": title,
        "minutes": minutes,
        "summary": summary,
        "sections": sections,
        "vocab": vocab,
        "exercises": exercises,
    }


COURSE = {
    "slug": "english",
    "title": "English",
    "short": "EN",
    "subtitle": "Грамматика, слова и задания — от A1 до B1",
    "category": "language",
    "accent": "#0d9488",
    "icon": "Aa",
    "blurb": "Нажмите на блок, выберите уровень и проходите уроки по порядку. В каждом уроке — правило простыми словами, таблица, примеры, карточки и проверка.",
    "levels": [
        {
            "slug": "a1",
            "short": "A1",
            "title": "A1 · Начало",
            "subtitle": "Простые предложения, to be, артикли, Present Simple",
            "lessons": [
                _lesson(
                    "greetings",
                    "Приветствие и алфавит",
                    10,
                    "Как поздороваться, представиться и прочитать английские буквы.",
                    [
                        {"type": "p", "text": "Английский алфавит — 26 букв. С него удобно начинать: вы сразу слышите, как звучит слово, и можете его прочитать по буквам (spell)."},
                        {"type": "h2", "text": "Как поздороваться"},
                        {"type": "table", "headers": ["Английский", "Когда говорить", "Русский"], "rows": [
                            ["Hello / Hi", "В любой ситуации / с друзьями", "Привет"],
                            ["Good morning", "До полудня", "Доброе утро"],
                            ["Good afternoon", "День", "Добрый день"],
                            ["Good evening", "Вечер", "Добрый вечер"],
                            ["Goodbye / Bye", "Прощание", "До свидания"],
                            ["Nice to meet you", "При знакомстве", "Приятно познакомиться"],
                        ]},
                        {"type": "h2", "text": "Как представиться"},
                        {"type": "pattern", "text": "My name is + имя.  ·  I am + имя.  ·  I'm + имя."},
                        {"type": "example", "en": "Hello! My name is Anna. I am from Spain.", "ru": "Привет! Меня зовут Анна. Я из Испании."},
                        {"type": "example", "en": "Hi, I'm Tom. Nice to meet you.", "ru": "Привет, я Том. Приятно познакомиться."},
                        {"type": "h2", "text": "Вежливые слова — говорите их часто"},
                        {"type": "ul", "items": [
                            "Please — пожалуйста (когда просите)",
                            "Thank you / Thanks — спасибо",
                            "You're welcome — пожалуйста (в ответ на спасибо)",
                            "Sorry / Excuse me — извините / простите (чтобы привлечь внимание)",
                            "Yes / No — да / нет",
                        ]},
                        {"type": "note", "text": "Excuse me — чтобы обратиться к незнакомцу. Sorry — если вы толкнули или опоздали."},
                    ],
                    [
                        _word("hello", "hello", "привет", "Hello, Maria!"),
                        _word("hi", "hi", "привет (неформально)", "Hi! How are you?"),
                        _word("name", "name", "имя", "My name is Alex."),
                        _word("please", "please", "пожалуйста", "A coffee, please."),
                        _word("thanks", "thank you", "спасибо", "Thank you very much."),
                        _word("sorry", "sorry", "извините", "Sorry, I'm late."),
                        _word("yes", "yes", "да", "Yes, I am."),
                        _word("no", "no", "нет", "No, thank you."),
                    ],
                    [
                        _ex("mcq", "Как неформально сказать «привет»?", "Hi", ["Good evening", "Hi", "Please", "Sorry"], "Hi — короткое и дружеское. Hello тоже можно всегда."),
                        _ex("mcq", "Что сказать при знакомстве?", "Nice to meet you", ["Good night", "You're welcome", "Nice to meet you", "Excuse me"], "Nice to meet you — стандартная фраза после имени."),
                        _ex("fill", "My name ____ Anna.", "is", None, "После name всегда is: My name is…"),
                        _ex("mcq", "Вы хотите попросить счёт. Какое слово добавить?", "please", ["sorry", "please", "bye", "no"], "A bill, please."),
                    ],
                ),
                _lesson(
                    "to-be",
                    "Глагол to be (am / is / are)",
                    14,
                    "Самый нужный глагол: кто вы, где вы, какой вы.",
                    [
                        {"type": "p", "text": "To be значит «быть». В настоящем времени он меняется: am, is, are. Без него нельзя сказать «я студент» или «это книга»."},
                        {"type": "h2", "text": "Формы"},
                        {"type": "table", "headers": ["Местоимение", "To be", "Кратко", "Пример"], "rows": [
                            ["I", "am", "I'm", "I am a student."],
                            ["he / she / it", "is", "he's / she's / it's", "She is a doctor."],
                            ["you / we / they", "are", "you're / we're / they're", "They are friends."],
                        ]},
                        {"type": "h2", "text": "Порядок слов"},
                        {"type": "pattern", "text": "Кто + am/is/are + кто/какой/где"},
                        {"type": "example", "en": "I am tired.", "ru": "Я устал(а)."},
                        {"type": "example", "en": "It is a cat.", "ru": "Это кот."},
                        {"type": "example", "en": "We are in London.", "ru": "Мы в Лондоне."},
                        {"type": "h2", "text": "Отрицание — добавьте not"},
                        {"type": "table", "headers": ["Полная форма", "Краткая"], "rows": [
                            ["I am not", "I'm not"],
                            ["he/she/it is not", "isn't"],
                            ["you/we/they are not", "aren't"],
                        ]},
                        {"type": "example", "en": "He isn't at home.", "ru": "Его нет дома."},
                        {"type": "h2", "text": "Вопрос — am/is/are вперёд"},
                        {"type": "pattern", "text": "Am/Is/Are + кто + … ?"},
                        {"type": "example", "en": "Are you ready?", "ru": "Ты готов?"},
                        {"type": "example", "en": "Is it cold?", "ru": "Холодно?"},
                        {"type": "note", "text": "Не говорите I student. Нужно I am a student. Артикль a разберём в следующем уроке."},
                    ],
                    [
                        _word("i-am", "I am / I'm", "я есть", "I'm happy."),
                        _word("he-is", "he is / he's", "он есть", "He is tall."),
                        _word("she-is", "she is / she's", "она есть", "She's a teacher."),
                        _word("it-is", "it is / it's", "это есть", "It's a book."),
                        _word("we-are", "we are / we're", "мы есть", "We're here."),
                        _word("they-are", "they are / they're", "они есть", "They're late."),
                        _word("isnt", "isn't", "не есть (he/she/it)", "It isn't far."),
                        _word("arent", "aren't", "не есть (you/we/they)", "We aren't ready."),
                    ],
                    [
                        _ex("mcq", "Выберите правильный вариант: She ____ a nurse.", "is", ["am", "is", "are", "be"], "She → is."),
                        _ex("mcq", "They ____ at school.", "are", ["am", "is", "are", "be"], "They → are."),
                        _ex("fill", "I ____ not a doctor. (краткая форма to be)", "am", None, "I am not / I'm not. Слово, которое спрягается — am."),
                        _ex("mcq", "Как задать вопрос «Ты студент?»", "Are you a student?", ["You are a student?", "Is you a student?", "Are you a student?", "You is a student?"], "Are + you + …"),
                        _ex("tf", "Предложение «He aren't happy» правильное.", "false", ["true", "false"], "He → isn't, не aren't."),
                    ],
                ),
                _lesson(
                    "articles",
                    "Артикли a / an / the",
                    12,
                    "Когда говорить «какой-то» и когда «тот самый».",
                    [
                        {"type": "p", "text": "В английском почти перед каждой исчисляемой вещью в единственном числе нужен артикль. Это не перевод «этот», а сигнал: вещь новая или уже известная."},
                        {"type": "h2", "text": "a / an — первый раз, один из многих"},
                        {"type": "ul", "items": [
                            "a — перед согласным звуком: a book, a university (звук «ю» — согласный)",
                            "an — перед гласным звуком: an apple, an hour (h не звучит)",
                        ]},
                        {"type": "example", "en": "I have a dog.", "ru": "У меня есть (какая-то) собака."},
                        {"type": "example", "en": "She is an engineer.", "ru": "Она инженер. (профессия в единственном числе — a/an)"},
                        {"type": "h2", "text": "the — уже понятно, о ком речь"},
                        {"type": "example", "en": "I have a dog. The dog is small.", "ru": "Собака уже известна — поэтому the."},
                        {"type": "ul", "items": [
                            "Единственная в контексте вещь: the sun, the door (дверь в этой комнате)",
                            "После первого упоминания: a café → the café",
                            "С порядковыми: the first, the next",
                        ]},
                        {"type": "h2", "text": "Нулевой артикль"},
                        {"type": "ul", "items": [
                            "Множественное число в общем смысле: Books are useful.",
                            "Имена: Anna, London (но the United States, the Thames)",
                            "Еда и вещества вообще: I like tea.",
                        ]},
                        {"type": "note", "text": "Смотрите на звук, не на букву: an hour, a house. University начинается на «ю» — a university."},
                    ],
                    [
                        _word("a", "a", "неопределённый артикль", "a cat"),
                        _word("an", "an", "артикля перед гласным звуком", "an orange"),
                        _word("the", "the", "определённый артикль", "the moon"),
                        _word("apple", "apple", "яблоко", "an apple"),
                        _word("hour", "hour", "час", "an hour"),
                        _word("house", "house", "дом", "a house"),
                    ],
                    [
                        _ex("mcq", "____ umbrella (зонтик начинается на гласный звук)", "an", ["a", "an", "the", "—"], "an umbrella"),
                        _ex("mcq", "I like ____ music. (музыка вообще)", "—", ["a", "an", "the", "—"], "Без артикля: I like music."),
                        _ex("fill", "This is ____ university. (напишите артикль a или an)", "a", None, "Звук «ю» — как согласный, поэтому a."),
                        _ex("mcq", "Open ____ window, please. (окно в этой комнате)", "the", ["a", "an", "the", "—"], "Конкретное окно — the."),
                    ],
                ),
                _lesson(
                    "pronouns",
                    "Местоимения и притяжательные",
                    12,
                    "I, you, my, your — кто говорит и чья это вещь.",
                    [
                        {"type": "p", "text": "Местоимение заменяет имя, чтобы не повторять его. Притяжательное слово отвечает на вопрос «чей?»."},
                        {"type": "h2", "text": "Личные (кто делает)"},
                        {"type": "table", "headers": ["Ед. число", "Мн. число"], "rows": [
                            ["I — я", "we — мы"],
                            ["you — ты / вы", "you — вы"],
                            ["he — он, she — она, it — оно/это", "they — они"],
                        ]},
                        {"type": "note", "text": "You — и «ты», и «вы». Отдельного «ты» нет. It — для вещей, животных (если не подчёркиваем пол) и идей."},
                        {"type": "h2", "text": "Притяжательные (чей?)"},
                        {"type": "table", "headers": ["Личное", "Притяжательное", "Пример"], "rows": [
                            ["I", "my", "my bag"],
                            ["you", "your", "your phone"],
                            ["he", "his", "his car"],
                            ["she", "her", "her name"],
                            ["it", "its", "its name"],
                            ["we", "our", "our house"],
                            ["they", "their", "their friends"],
                        ]},
                        {"type": "example", "en": "This is my brother. His name is Leo.", "ru": "Это мой брат. Его зовут Лео."},
                        {"type": "h2", "text": "its ≠ it's"},
                        {"type": "ul", "items": [
                            "it's = it is (это есть)",
                            "its = его/её (принадлежит вещи): The cat ate its food.",
                        ]},
                    ],
                    [
                        _word("i", "I", "я", "I am here."),
                        _word("you", "you", "ты / вы", "You are kind."),
                        _word("he", "he", "он", "He is my father."),
                        _word("she", "she", "она", "She is my mother."),
                        _word("we", "we", "мы", "We are a family."),
                        _word("my", "my", "мой / моя / моё", "This is my book."),
                        _word("your", "your", "твой / ваш", "What's your name?"),
                        _word("his", "his", "его", "his bag"),
                        _word("her", "her", "её", "her bag"),
                        _word("their", "their", "их", "their house"),
                    ],
                    [
                        _ex("mcq", "This is Anna. ____ name is Anna.", "Her", ["His", "Her", "Its", "Your"], "Anna — she → her."),
                        _ex("mcq", "We have a house. It's ____ house.", "our", ["our", "us", "we", "their"], "we → our"),
                        _ex("fill", "____ am a teacher. (местоимение «я»)", "I", None, "I всегда с большой буквы."),
                        _ex("tf", "it's и its — одно и то же.", "false", ["true", "false"], "it's = it is; its = чей-то (у вещи)."),
                    ],
                ),
                _lesson(
                    "present-simple",
                    "Present Simple",
                    16,
                    "Факты, привычки, расписание. Окончание -s у he/she/it.",
                    [
                        {"type": "p", "text": "Present Simple — время «вообще»: что человек делает обычно, что всегда правда, что стоит в расписании. Не путайте с «прямо сейчас» — это другое время (Present Continuous, уровень A2)."},
                        {"type": "h2", "text": "Утверждение"},
                        {"type": "pattern", "text": "I/you/we/they + глагол   ·   he/she/it + глагол-s"},
                        {"type": "table", "headers": ["Подлежащее", "Глагол", "Пример"], "rows": [
                            ["I / you / we / they", "work, go, play", "I work in an office."],
                            ["he / she / it", "works, goes, plays", "She works in a hospital."],
                        ]},
                        {"type": "h2", "text": "Как появляется -s"},
                        {"type": "ul", "items": [
                            "Обычно просто +s: play → plays, live → lives",
                            "-ch, -sh, -s, -x, -o → +es: watch → watches, go → goes",
                            "согласная + y → -ies: study → studies (но play → plays: y после гласной)",
                            "have → has (исключение)",
                        ]},
                        {"type": "h2", "text": "Отрицание и вопрос — нужен do/does"},
                        {"type": "table", "headers": ["", "I/you/we/they", "he/she/it"], "rows": [
                            ["Отрицание", "do not (don't) + глагол", "does not (doesn't) + глагол"],
                            ["Вопрос", "Do they live here?", "Does she live here?"],
                        ]},
                        {"type": "example", "en": "I don't drink coffee.", "ru": "Я не пью кофе. (после don't глагол без -s)"},
                        {"type": "example", "en": "Does he speak English? — Yes, he does.", "ru": "После does глагол тоже «голый»: speak, не speaks."},
                        {"type": "h2", "text": "Слова-подсказки"},
                        {"type": "ul", "items": ["always, usually, often, sometimes, never", "every day / every morning", "on Mondays, at 7 o'clock (расписание)"]},
                        {"type": "note", "text": "Does + speaks — ошибка. Does уже «несёт» окончание. Пишите Does she speak?"},
                    ],
                    [
                        _word("work", "work / works", "работать", "He works here."),
                        _word("live", "live / lives", "жить", "I live in Berlin."),
                        _word("go", "go / goes", "идти, ехать", "She goes to school."),
                        _word("have", "have / has", "иметь", "He has a car."),
                        _word("dont", "don't", "не (I/you/we/they)", "I don't know."),
                        _word("doesnt", "doesn't", "не (he/she/it)", "She doesn't drive."),
                        _word("always", "always", "всегда", "I always get up at 7."),
                        _word("never", "never", "никогда", "He never smokes."),
                    ],
                    [
                        _ex("mcq", "She ____ English every day.", "studies", ["study", "studys", "studies", "studying"], "she + study → studies."),
                        _ex("mcq", "____ they like pizza?", "Do", ["Do", "Does", "Are", "Is"], "they → Do."),
                        _ex("fill", "He ____ not play football. (does / do)", "does", None, "he → does not / doesn't."),
                        _ex("tf", "В вопросе «Does she likes tea?» всё верно.", "false", ["true", "false"], "Нужно Does she like tea?"),
                        _ex("mcq", "I ____ to work by bus.", "go", ["go", "goes", "going", "went"], "I → глагол без -s."),
                    ],
                ),
                _lesson(
                    "there-is",
                    "There is / there are",
                    10,
                    "Как сказать «есть / находится» про вещи в месте.",
                    [
                        {"type": "p", "text": "Когда хотите сказать, что в комнате, городе или сумке что-то есть, начинайте с there is / there are. Это не «там» в смысле указания пальцем — это конструкция «имеется»."},
                        {"type": "pattern", "text": "There is + единственное   ·   There are + множественное"},
                        {"type": "example", "en": "There is a cat on the sofa.", "ru": "На диване (есть) кот."},
                        {"type": "example", "en": "There are two books on the table.", "ru": "На столе две книги."},
                        {"type": "h2", "text": "Отрицание и вопрос"},
                        {"type": "ul", "items": [
                            "There isn't a park here. / There aren't any shops.",
                            "Is there a bank near here? — Yes, there is.",
                            "Are there any questions? — No, there aren't.",
                        ]},
                        {"type": "h2", "text": "some и any"},
                        {"type": "ul", "items": [
                            "some — в утверждениях: There are some apples.",
                            "any — в вопросах и отрицаниях: Are there any apples? There aren't any apples.",
                        ]},
                        {"type": "note", "text": "It is a cat = это кот (называем). There is a cat = кот есть (в этом месте)."},
                    ],
                    [
                        _word("there-is", "there is / there's", "есть (ед. ч.)", "There's a problem."),
                        _word("there-are", "there are", "есть (мн. ч.)", "There are three rooms."),
                        _word("some", "some", "несколько / немного", "some water"),
                        _word("any", "any", "какие-либо (в вопросе/отрицании)", "Have you got any milk?"),
                        _word("near", "near", "рядом", "near the school"),
                        _word("on", "on", "на (поверхности)", "on the table"),
                    ],
                    [
                        _ex("mcq", "____ a supermarket in this street.", "There is", ["There is", "There are", "It is", "They are"], "Один супермаркет — there is."),
                        _ex("mcq", "____ many people in the park.", "There are", ["There is", "There are", "It is", "There"], "many people — множественное."),
                        _ex("fill", "Is ____ a hotel here?", "there", None, "Is there a …?"),
                        _ex("mcq", "There aren't ____ chairs.", "any", ["some", "any", "a", "the"], "Отрицание → any."),
                    ],
                ),
                _lesson(
                    "questions",
                    "Вопросы: yes/no и Wh-",
                    12,
                    "Do, does, is и слова what, where, who, when, why, how.",
                    [
                        {"type": "p", "text": "В английском вопрос почти всегда начинается со вспомогательного слова. Не оставляйте глагол на месте, как в русском «Ты живёшь здесь?»."},
                        {"type": "h2", "text": "Yes / no вопросы"},
                        {"type": "table", "headers": ["Глагол в предложении", "Как спросить"], "rows": [
                            ["to be: You are tired.", "Are you tired?"],
                            ["have got: She has got a car. (британский)", "Has she got a car?"],
                            ["другие глаголы", "Do/Does + подлежащее + глагол?"],
                        ]},
                        {"type": "example", "en": "Do you like tea? — Yes, I do. / No, I don't.", "ru": "Короткий ответ повторяет do/does, не like."},
                        {"type": "h2", "text": "Wh- вопросы — сначала вопросительное слово"},
                        {"type": "table", "headers": ["Слово", "Спрашивает"], "rows": [
                            ["What", "что / какой"],
                            ["Where", "где / куда"],
                            ["When", "когда"],
                            ["Who", "кто"],
                            ["Why", "почему"],
                            ["How", "как"],
                            ["How old / How much / How many", "сколько лет / сколько (неисчисл.) / сколько (штук)"],
                        ]},
                        {"type": "pattern", "text": "Wh- + do/does/is/are + подлежащее + глагол?"},
                        {"type": "example", "en": "Where do you live?", "ru": "Где ты живёшь?"},
                        {"type": "example", "en": "What is her name?", "ru": "Как её зовут? (буквально: какое её имя?)"},
                        {"type": "note", "text": "Who is that? — если who само является подлежащим, do не нужен: Who lives here?"},
                    ],
                    [
                        _word("what", "what", "что / какой", "What is this?"),
                        _word("where", "where", "где", "Where are you?"),
                        _word("when", "when", "когда", "When do you start?"),
                        _word("who", "who", "кто", "Who is he?"),
                        _word("why", "why", "почему", "Why are you late?"),
                        _word("how", "how", "как", "How are you?"),
                        _word("how-old", "how old", "сколько лет", "How old are you?"),
                    ],
                    [
                        _ex("mcq", "____ do you live?", "Where", ["What", "Where", "Who", "Why"], "Where — где."),
                        _ex("mcq", "____ she like coffee?", "Does", ["Do", "Does", "Is", "Are"], "she → Does."),
                        _ex("fill", "____ is your name?", "What", None, "What is your name?"),
                        _ex("mcq", "How ____ is your brother?", "old", ["old", "many", "much", "age"], "How old — возраст."),
                    ],
                ),
                _lesson(
                    "everyday-words",
                    "Слова на каждый день",
                    12,
                    "Семья, дом, еда и простые предлоги места.",
                    [
                        {"type": "p", "text": "Грамматика без слов не работает. Заучите небольшими группами и сразу составляйте фразы с to be и there is."},
                        {"type": "h2", "text": "Семья"},
                        {"type": "table", "headers": ["English", "Русский"], "rows": [
                            ["mother / mum", "мама"],
                            ["father / dad", "папа"],
                            ["brother / sister", "брат / сестра"],
                            ["son / daughter", "сын / дочь"],
                            ["friend", "друг / подруга"],
                        ]},
                        {"type": "h2", "text": "Дом и еда"},
                        {"type": "ul", "items": [
                            "house, room, kitchen, bathroom, door, window, table, chair, bed",
                            "water, tea, coffee, bread, apple, breakfast, lunch, dinner",
                        ]},
                        {"type": "h2", "text": "Предлоги места"},
                        {"type": "table", "headers": ["Предлог", "Смысл", "Пример"], "rows": [
                            ["in", "внутри", "in the room"],
                            ["on", "на поверхности", "on the table"],
                            ["under", "под", "under the chair"],
                            ["next to", "рядом с", "next to the door"],
                            ["between", "между", "between the beds"],
                        ]},
                        {"type": "example", "en": "My keys are on the table, next to the book.", "ru": "Мои ключи на столе, рядом с книгой."},
                    ],
                    [
                        _word("mother", "mother", "мама", "This is my mother."),
                        _word("father", "father", "папа", "My father is a driver."),
                        _word("family", "family", "семья", "I love my family."),
                        _word("house", "house", "дом", "Our house is small."),
                        _word("water", "water", "вода", "I drink water."),
                        _word("breakfast", "breakfast", "завтрак", "Breakfast is at 8."),
                        _word("in", "in", "в (внутри)", "in the bag"),
                        _word("under", "under", "под", "under the bed"),
                        _word("next-to", "next to", "рядом с", "next to me"),
                    ],
                    [
                        _ex("mcq", "The cat is ____ the table. (на столе)", "on", ["in", "on", "under", "between"], "on — на поверхности."),
                        _ex("mcq", "I have breakfast in the ____.", "kitchen", ["bathroom", "kitchen", "window", "door"], "Завтрак обычно на кухне."),
                        _ex("fill", "This is my ____. Her name is Eva. (сестра)", "sister", None, "sister"),
                        _ex("mcq", "The shoes are ____ the bed. (под кроватью)", "under", ["on", "in", "under", "next"], "under the bed"),
                    ],
                ),
            ],
        },
        {
            "slug": "a2",
            "short": "A2",
            "title": "A2 · База",
            "subtitle": "Прошедшее, «прямо сейчас», сравнение, планы и модальные глаголы",
            "lessons": [
                _lesson(
                    "past-simple",
                    "Past Simple",
                    16,
                    "Что случилось вчера: правильные -ed и список неправильных.",
                    [
                        {"type": "p", "text": "Past Simple — законченное действие в прошлом. Есть маркер времени: yesterday, last week, in 2020, two days ago."},
                        {"type": "h2", "text": "Правильные глаголы: +ed"},
                        {"type": "ul", "items": [
                            "work → worked, play → played",
                            "e на конце: live → lived",
                            "согласная + y: study → studied",
                            "короткая гласная + согласная: stop → stopped",
                        ]},
                        {"type": "h2", "text": "Неправильные — запоминать целиком"},
                        {"type": "table", "headers": ["Сейчас", "Прошлое", "Русский"], "rows": [
                            ["go", "went", "идти / ехать"],
                            ["have", "had", "иметь"],
                            ["do", "did", "делать"],
                            ["see", "saw", "видеть"],
                            ["come", "came", "приходить"],
                            ["eat", "ate", "есть"],
                            ["be", "was / were", "быть"],
                        ]},
                        {"type": "note", "text": "I/he/she/it was · you/we/they were. There was a cat. There were two cats."},
                        {"type": "h2", "text": "Отрицание и вопрос — всегда did"},
                        {"type": "pattern", "text": "did not (didn't) + глагол в первой форме    Did + кто + глагол?"},
                        {"type": "example", "en": "I didn't go out yesterday.", "ru": "Не I didn't went — после didn't глагол без прошедшего."},
                        {"type": "example", "en": "Did you see the film? — Yes, I did.", "ru": "Короткий ответ: did, не saw."},
                    ],
                    [
                        _word("yesterday", "yesterday", "вчера", "I was tired yesterday."),
                        _word("went", "went", "went ← go", "We went home."),
                        _word("had", "had", "had ← have", "I had breakfast."),
                        _word("did", "did / didn't", "вспомогательный в прошлом", "Did you call?"),
                        _word("was", "was", "was ← be (I/he/she/it)", "She was late."),
                        _word("were", "were", "were ← be (you/we/they)", "They were at home."),
                        _word("last-week", "last week", "на прошлой неделе", "I saw her last week."),
                    ],
                    [
                        _ex("mcq", "They ____ to Paris last year.", "went", ["go", "goes", "went", "gone"], "last year → Past Simple, go → went."),
                        _ex("mcq", "I ____ not watch TV yesterday.", "did", ["do", "did", "was", "were"], "didn't watch."),
                        _ex("fill", "____ you see him? (Did / Do)", "Did", None, "Прошлое → Did."),
                        _ex("tf", "She didn't went to school — правильная фраза.", "false", ["true", "false"], "didn't go."),
                    ],
                ),
                _lesson(
                    "present-continuous",
                    "Present Continuous",
                    12,
                    "Действие прямо сейчас или временная ситуация.",
                    [
                        {"type": "pattern", "text": "am / is / are + глагол-ing"},
                        {"type": "example", "en": "I am reading now.", "ru": "Я (сейчас) читаю."},
                        {"type": "example", "en": "She is working this week.", "ru": "На этой неделе — временно, не «вообще»."},
                        {"type": "h2", "text": "Когда так говорить"},
                        {"type": "ul", "items": [
                            "now, at the moment, Look!, Listen!",
                            "временные планы сегодня/на этот период: I'm staying with a friend this month.",
                        ]},
                        {"type": "h2", "text": "Не путать с Present Simple"},
                        {"type": "table", "headers": ["Simple — обычно", "Continuous — сейчас"], "rows": [
                            ["I work in a bank.", "I am working on a report now."],
                            ["He speaks Spanish.", "He is speaking on the phone."],
                        ]},
                        {"type": "h2", "text": "-ing без ловушек"},
                        {"type": "ul", "items": ["make → making (e пропадает)", "sit → sitting (согласная удваивается)", "lie → lying"]},
                        {"type": "note", "text": "Глаголы состояния обычно без -ing: know, like, want, have (в значении «иметь»). Не I am knowing — I know."},
                    ],
                    [
                        _word("now", "now", "сейчас", "I'm busy now."),
                        _word("reading", "reading", "читаю (ing)", "She is reading."),
                        _word("working", "working", "работаю (ing)", "We are working."),
                        _word("at-the-moment", "at the moment", "в данный момент", "He's cooking at the moment."),
                    ],
                    [
                        _ex("mcq", "Look! It ____.", "is raining", ["rains", "is raining", "rain", "rained"], "Look! → Continuous."),
                        _ex("mcq", "I ____ coffee every morning. (привычка)", "drink", ["drink", "am drinking", "drinks", "drank"], "every morning → Simple."),
                        _ex("fill", "They ____ watching a film. (are / is)", "are", None, "they are"),
                        _ex("tf", "I am wanting a sandwich — так говорят.", "false", ["true", "false"], "I want a sandwich."),
                    ],
                ),
                _lesson(
                    "comparatives",
                    "Сравнение: -er, more, the most",
                    12,
                    "Как сказать «выше», «более интересный», «самый».",
                    [
                        {"type": "h2", "text": "Короткие прилагательные — -er / -est"},
                        {"type": "example", "en": "tall → taller → the tallest", "ru": "высокий — выше — самый высокий"},
                        {"type": "ul", "items": ["big → bigger (удваивание)", "nice → nicer", "happy → happier"]},
                        {"type": "h2", "text": "Длинные — more / the most"},
                        {"type": "example", "en": "interesting → more interesting → the most interesting", "ru": "Для слов в 2+ слога, кроме простых вроде happy, easy, simple."},
                        {"type": "h2", "text": "Исключения — выучить"},
                        {"type": "table", "headers": ["Прилагательное", "Сравнительная", "Превосходная"], "rows": [
                            ["good", "better", "the best"],
                            ["bad", "worse", "the worst"],
                            ["far", "farther / further", "the farthest / furthest"],
                        ]},
                        {"type": "pattern", "text": "A is taller than B.   ·   A is as tall as B. (такой же)"},
                    ],
                    [
                        _word("taller", "taller", "выше", "She is taller than me."),
                        _word("better", "better", "лучше", "This is better."),
                        _word("worse", "worse", "хуже", "The weather is worse today."),
                        _word("than", "than", "чем (при сравнении)", "older than"),
                        _word("most", "the most", "самый (для длинных слов)", "the most popular"),
                    ],
                    [
                        _ex("mcq", "This bag is ____ than that one.", "cheaper", ["cheap", "cheaper", "cheapest", "more cheap"], "короткое слово → cheaper."),
                        _ex("mcq", "This is ____ film of the year.", "the best", ["better", "the best", "good", "more good"], "из всех — the best."),
                        _ex("fill", "He is older ____ me.", "than", None, "than, не then."),
                    ],
                ),
                _lesson(
                    "modals",
                    "Can, must, should",
                    12,
                    "Умение, обязанность и совет — без to после них.",
                    [
                        {"type": "p", "text": "Модальные глаголы стоят перед смысловым глаголом и не принимают -s: she can swim, не she cans."},
                        {"type": "table", "headers": ["Глагол", "Смысл", "Отрицание"], "rows": [
                            ["can", "умею / могу / разрешено", "can't"],
                            ["must", "должен (сильная обязанность или запрет must not)", "mustn't = нельзя"],
                            ["should", "стоит / советую", "shouldn't"],
                            ["have to", "вынужден (правило, обстоятельство)", "don't have to = не обязательно"],
                        ]},
                        {"type": "example", "en": "You can take a day off.", "ru": "Можешь взять выходной."},
                        {"type": "example", "en": "You mustn't smoke here.", "ru": "Здесь нельзя курить."},
                        {"type": "example", "en": "You don't have to come.", "ru": "Не обязан приходить (но можно)."},
                        {"type": "note", "text": "mustn't ≠ don't have to. Первое — запрет. Второе — нет необходимости."},
                    ],
                    [
                        _word("can", "can", "мочь / уметь", "I can swim."),
                        _word("cant", "can't", "не могу", "I can't drive."),
                        _word("must", "must", "должен", "You must stop."),
                        _word("should", "should", "следует", "You should rest."),
                        _word("have-to", "have to", "приходится", "I have to work."),
                    ],
                    [
                        _ex("mcq", "I'm sorry, I ____ help you now.", "can't", ["can't", "must", "should", "have"], "can't — не могу."),
                        _ex("mcq", "It's a secret. You ____ tell anyone.", "mustn't", ["mustn't", "don't have to", "should", "can"], "Запрет — mustn't."),
                        _ex("fill", "You ____ see a doctor. (совет: should / can)", "should", None, "should — совет."),
                    ],
                ),
                _lesson(
                    "future",
                    "Будущее: going to и will",
                    12,
                    "План уже есть — going to. Решение сейчас или обещание — will.",
                    [
                        {"type": "h2", "text": "be going to — намерение и признаки"},
                        {"type": "pattern", "text": "am/is/are + going to + глагол"},
                        {"type": "example", "en": "I'm going to study medicine.", "ru": "План уже принят."},
                        {"type": "example", "en": "Look at those clouds. It's going to rain.", "ru": "По признакам видно, что случится."},
                        {"type": "h2", "text": "will — обещание, прогноз, решение в момент речи"},
                        {"type": "pattern", "text": "will + глагол     won't = will not"},
                        {"type": "example", "en": "It's cold. I'll close the window.", "ru": "Решил только что."},
                        {"type": "example", "en": "I think she will pass the exam.", "ru": "Мнение о будущем."},
                        {"type": "note", "text": "Для расписания транспорта и афиш часто хватает Present Simple: The train leaves at 6."},
                    ],
                    [
                        _word("going-to", "going to", "собираюсь", "I'm going to call her."),
                        _word("will", "will", "will (будущее)", "I will help you."),
                        _word("wont", "won't", "не буду", "I won't forget."),
                        _word("tomorrow", "tomorrow", "завтра", "See you tomorrow."),
                    ],
                    [
                        _ex("mcq", "We have tickets. We ____ visit Rome in May.", "are going to", ["will", "are going to", "go", "going"], "Билеты уже есть — план, going to."),
                        _ex("mcq", "The phone is ringing. I ____ it.", "I'll get", ["I'll get", "I'm going to get", "I get", "I got"], "Решение сейчас — will."),
                        _ex("fill", "She ____ not come tonight. (won't → вспомогательный глагол)", "will", None, "will not / won't."),
                    ],
                ),
            ],
        },
        {
            "slug": "b1",
            "short": "B1",
            "title": "B1 · Уверенность",
            "subtitle": "Present Perfect, условия, пассив и относительные предложения",
            "lessons": [
                _lesson(
                    "present-perfect",
                    "Present Perfect",
                    16,
                    "Опыт и связь с настоящим: have/has + 3-я форма.",
                    [
                        {"type": "pattern", "text": "have / has + Past Participle (3-я форма)"},
                        {"type": "p", "text": "Это не «просто прошлое». Мы говорим о результате или опыте, который важен сейчас. Когда точно — часто неважно, или период ещё не закончен (today, this week, ever, never, already, yet, just)."},
                        {"type": "example", "en": "I have lost my keys.", "ru": "Ключи потеряны (и сейчас их нет). Не важно, в какой минуте."},
                        {"type": "example", "en": "She has lived here for 3 years.", "ru": "Живёт до сих пор. for — период, since — точка старта."},
                        {"type": "h2", "text": "Не путать с Past Simple"},
                        {"type": "table", "headers": ["Present Perfect", "Past Simple"], "rows": [
                            ["I have seen this film.", "I saw it yesterday."],
                            ["Have you ever been to Japan?", "When did you go?"],
                        ]},
                        {"type": "ul", "items": [
                            "ever / never / already / yet / just — типичные спутники Perfect",
                            "ago, last year, when? — почти всегда Past Simple",
                        ]},
                        {"type": "note", "text": "been = ездил и вернулся. gone = уехал и его нет: She has gone to work."},
                    ],
                    [
                        _word("have-pp", "have / has + V3", "Present Perfect", "I have finished."),
                        _word("already", "already", "уже", "I have already eaten."),
                        _word("yet", "yet", "уже / ещё (в вопросе и отрицании)", "Has she arrived yet?"),
                        _word("just", "just", "только что", "He has just left."),
                        _word("ever", "ever", "когда-либо", "Have you ever tried sushi?"),
                        _word("since", "since", "с (какого момента)", "since 2020"),
                        _word("for", "for", "в течение", "for two hours"),
                    ],
                    [
                        _ex("mcq", "I ____ my homework, so I can go out.", "have finished", ["finished", "have finished", "finish", "am finishing"], "Результат сейчас — Perfect."),
                        _ex("mcq", "I ____ this film last night.", "saw", ["have seen", "saw", "seen", "see"], "last night → Past Simple."),
                        _ex("fill", "She has lived here ____ 2019. (since / for)", "since", None, "since + точка во времени."),
                        _ex("tf", "I have seen him yesterday — нормально.", "false", ["true", "false"], "yesterday требует Past Simple: I saw him yesterday."),
                    ],
                ),
                _lesson(
                    "conditionals",
                    "First conditional",
                    12,
                    "Реальное будущее: If + Present, will…",
                    [
                        {"type": "pattern", "text": "If + Present Simple, will + глагол"},
                        {"type": "example", "en": "If it rains, we will stay at home.", "ru": "Если (в будущем) пойдёт дождь, останемся дома."},
                        {"type": "p", "text": "В if-части не ставьте will. Will — только в результате. Порядок частей можно менять: We'll stay at home if it rains. Запятая нужна, когда if стоит первым."},
                        {"type": "h2", "text": "Рядом: zero conditional"},
                        {"type": "pattern", "text": "If + Present, Present — всегда правда, научные факты, привычки"},
                        {"type": "example", "en": "If you heat ice, it melts.", "ru": "Не про будущее, а про закон природы."},
                        {"type": "note", "text": "Unless = if not: Unless you hurry, you'll miss the bus."},
                    ],
                    [
                        _word("if", "if", "если", "If I have time, I'll call."),
                        _word("unless", "unless", "если не", "Unless it rains, we go."),
                        _word("will-if", "If + present, will…", "реальное будущее", "If she studies, she will pass."),
                    ],
                    [
                        _ex("mcq", "If I ____ late, I will take a taxi.", "am", ["will be", "am", "was", "be"], "В if — Present: If I am late."),
                        _ex("mcq", "If you heat water to 100°C, it ____.", "boils", ["will boil", "boils", "boiled", "is boiling"], "Факт — zero conditional, Present в обеих частях. will boil тоже часто говорят, но классика — boils."),
                        _ex("fill", "If she ____, she will miss the train. (hurry / hurries — нужна форма после if she)", "hurries", None, "If she hurries — Present Simple для she."),
                    ],
                ),
                _lesson(
                    "passive",
                    "Passive Voice",
                    12,
                    "Когда важен объект, а не тот, кто сделал: be + V3.",
                    [
                        {"type": "pattern", "text": "am/is/are + V3     was/were + V3"},
                        {"type": "example", "en": "English is spoken here.", "ru": "Здесь говорят по-английски. Кто именно — неважно."},
                        {"type": "example", "en": "The letters were sent yesterday.", "ru": "Письма отправили вчера."},
                        {"type": "h2", "text": "Зачем это нужно"},
                        {"type": "ul", "items": [
                            "Не знаем или не хотим называть деятеля",
                            "Научный и новостной стиль: The patient was examined.",
                            "Если деятель важен — добавьте by: The book was written by her.",
                        ]},
                        {"type": "table", "headers": ["Active", "Passive"], "rows": [
                            ["They make cars here.", "Cars are made here."],
                            ["Someone stole my bag.", "My bag was stolen."],
                        ]},
                    ],
                    [
                        _word("is-made", "is made", "делается (пассив)", "It is made in Japan."),
                        _word("was-stolen", "was stolen", "был украден", "My bike was stolen."),
                        _word("by", "by", "кем (в пассиве)", "written by Tolstoy"),
                    ],
                    [
                        _ex("mcq", "This room ____ every day.", "is cleaned", ["cleans", "is cleaned", "cleaned", "is cleaning"], "Комнату убирают — пассив."),
                        _ex("fill", "The window ____ broken yesterday. (was / is)", "was", None, "yesterday → was broken."),
                        _ex("mcq", "The film was directed ____ Nolan.", "by", ["from", "by", "with", "of"], "by + деятель."),
                    ],
                ),
                _lesson(
                    "relative-clauses",
                    "Who, which, that",
                    10,
                    "Придаточные, которые уточняют, о ком и о чём речь.",
                    [
                        {"type": "table", "headers": ["Слово", "Для кого"], "rows": [
                            ["who", "люди"],
                            ["which", "вещи и животные"],
                            ["that", "люди и вещи (в определяющих придаточных)"],
                            ["where", "места"],
                        ]},
                        {"type": "example", "en": "The woman who called you is my aunt.", "ru": "Женщина, которая вам звонила, — моя тётя."},
                        {"type": "example", "en": "This is the book that I told you about.", "ru": "Это книга, о которой я говорил."},
                        {"type": "note", "text": "В разговорном языке that часто заменяет who/which в нужной информации: the phone that I bought. Если без придаточного смысл ломается — запятые не ставят."},
                    ],
                    [
                        _word("who", "who", "который (о людях)", "the man who…"),
                        _word("which", "which", "который (о вещах)", "the car which…"),
                        _word("that-rel", "that", "который (универсально)", "the film that…"),
                        _word("where-rel", "where", "где (о месте)", "the city where I live"),
                    ],
                    [
                        _ex("mcq", "That's the doctor ____ helped me.", "who", ["which", "who", "where", "what"], "doctor — человек → who."),
                        _ex("mcq", "This is the café ____ we met.", "where", ["who", "which", "where", "that"], "место → where (или which we met in)."),
                        _ex("fill", "A thermometer is a tool ____ measures temperature. (which/who)", "which", None, "tool — вещь → which/that."),
                    ],
                ),
            ],
        },
    ],
}
