services:
  - type: web
    name: daily-goals
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
