-- Isolated schema so this app can share a Supabase project with other services
-- without colliding with their public tables. The Flask app sets search_path
-- to daily_goals and talks to Postgres directly (not PostgREST).

CREATE SCHEMA IF NOT EXISTS daily_goals;

CREATE TABLE IF NOT EXISTS daily_goals.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower
    ON daily_goals.users (LOWER(username));

CREATE TABLE IF NOT EXISTS daily_goals.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_goals.completions (
    goal_id BIGINT NOT NULL REFERENCES daily_goals.goals(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    done INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (goal_id, date)
);

CREATE TABLE IF NOT EXISTS daily_goals.synced_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,
    date TEXT NOT NULL,
    text TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT '',
    task_type TEXT NOT NULL DEFAULT 'Task',
    done INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, external_id)
);

CREATE TABLE IF NOT EXISTS daily_goals.synced_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    options_json TEXT NOT NULL DEFAULT '[]',
    example TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    due TEXT NOT NULL DEFAULT '0000-00-00',
    interval INTEGER NOT NULL DEFAULT 1,
    ease DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    reps INTEGER NOT NULL DEFAULT 0,
    lapses INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, external_id)
);

CREATE TABLE IF NOT EXISTS daily_goals.card_review_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,
    confidence INTEGER NOT NULL DEFAULT 3,
    reviewed_at TEXT NOT NULL,
    consumed INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_card_review_events_user_consumed
    ON daily_goals.card_review_events (user_id, consumed, reviewed_at);

CREATE TABLE IF NOT EXISTS daily_goals.new_card_intro_state (
    user_id BIGINT PRIMARY KEY REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    ids_json TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS daily_goals.synced_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,
    title TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    content BYTEA NOT NULL,
    UNIQUE (user_id, external_id)
);

ALTER TABLE daily_goals.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.synced_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.synced_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.card_review_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.new_card_intro_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.synced_books ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON SCHEMA daily_goals FROM PUBLIC;
REVOKE ALL ON SCHEMA daily_goals FROM anon, authenticated;
GRANT USAGE ON SCHEMA daily_goals TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA daily_goals TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA daily_goals TO postgres;
