-- Learn courses progress, Anki-style card fields, reader highlights, SRS settings.

ALTER TABLE daily_goals.synced_cards ADD COLUMN IF NOT EXISTS queue INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_goals.synced_cards ADD COLUMN IF NOT EXISTS due_at TEXT NOT NULL DEFAULT '';
ALTER TABLE daily_goals.synced_cards ADD COLUMN IF NOT EXISTS learn_step INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_goals.synced_cards ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'desktop';

CREATE TABLE IF NOT EXISTS daily_goals.srs_settings (
    user_id BIGINT PRIMARY KEY REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    new_per_day INTEGER NOT NULL DEFAULT 20,
    reviews_per_day INTEGER NOT NULL DEFAULT 200,
    notify_enabled INTEGER NOT NULL DEFAULT 1,
    notify_hour INTEGER NOT NULL DEFAULT 9
);

CREATE TABLE IF NOT EXISTS daily_goals.srs_day_counts (
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    new_shown INTEGER NOT NULL DEFAULT 0,
    reviews_shown INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, date)
);

CREATE TABLE IF NOT EXISTS daily_goals.lesson_progress (
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    course_slug TEXT NOT NULL,
    lesson_slug TEXT NOT NULL,
    grammar_done INTEGER NOT NULL DEFAULT 0,
    cards_added INTEGER NOT NULL DEFAULT 0,
    exercises_correct INTEGER NOT NULL DEFAULT 0,
    exercises_total INTEGER NOT NULL DEFAULT 0,
    answers_json TEXT NOT NULL DEFAULT '{}',
    completed INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (user_id, course_slug, lesson_slug)
);

CREATE TABLE IF NOT EXISTS daily_goals.book_highlights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES daily_goals.users(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES daily_goals.synced_books(id) ON DELETE CASCADE,
    start_offset INTEGER NOT NULL DEFAULT 0,
    end_offset INTEGER NOT NULL DEFAULT 0,
    color TEXT NOT NULL DEFAULT 'yellow',
    snippet TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_book_highlights_user_book
    ON daily_goals.book_highlights (user_id, book_id);

UPDATE daily_goals.synced_cards SET queue = 2 WHERE reps > 0 AND queue = 0;

ALTER TABLE daily_goals.srs_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.srs_day_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals.book_highlights ENABLE ROW LEVEL SECURITY;

GRANT ALL ON ALL TABLES IN SCHEMA daily_goals TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA daily_goals TO postgres;
